### ISSUE TITLE
Do not separate multiple discs in albums (and every) views

### ISSUE THREAD

**Issue by krodelabestiole** [ampache/ampache#1015]
i spent a long time wondering why "Group multiple disks" had no effects before i understand it just changes the way albums are displayed in the "artist" view.

> the disks are grouped only into the artist view. If you search or go directly to albums list for example, you'll still see one line per album (that's voluntary to let the user the possibility to edit settings per album without the need to go each time into the artist.)

https://github.com/ampache/ampache/issues/136
well i can understand the reason why someone would want to edit just one disc, but in that case they could just uncheck this setting ?
choosing this option i think it would make more sense that multiple discs diplay as one album, everywhere... at least it make more sense for simple listeners (and mobile clients), for one release is one release (sorry for the tautology, but you've got my point ?).

**Comment by apastuszak** [comment]
I'm curious what the plan is for this.  Which release is it targeted for?

**Comment by apastuszak** [comment]
My quarterly nag.  This is making my Subsonic client a mess.  Just curious what the long term plan for this is.

**Comment by kuzi-moto** [comment]
+1 not a fan of separating the discs. I can't imagine many situations you would prefer separating them.

**Comment by apastuszak** [comment]
I appears that Ampache creates a unique disc ID for each disc.  So a 2 disc
album will have 2 different IDs.  When a subsonic client sees this, it
treats them as separate albums.  The subsonic client is looking for the
same disc ID but with different disc number tags.

So, I can see how making sure multi-disc albums have one common disc ID is
a petty big change for Ampache and probably needs a lot of coding work.

I'm just curious if this is planned for a certain release, or even on the
roadmap.

If I knew even a little bit of php, I might take a crack at it, but I'm
clueless.

Having played with pretty much every music streaming server, ampache is
best of breed right now.  I wish someone would write a client that uses the
Ampache APIs, instead of the subsonic ones.

**Comment by Phyks** [comment]
:+1: there are some things to do around this.

This is also something I noted when working on an alternative interface plugged into Ampache through the API (https://github.com/ampache/ampache/issues/1292#issuecomment-229714456) and I will try to tackle it at some point.

Actually, the Ampache XML API returns (as the Subsonic API I guess) two distinct albums elements with different fields and same `mbid` (if any). Then, it is really difficult to discover these albums are actually different disks from the same single album.

I am not sure if I should rework the API part (both XML and Subsonic) to expose it directly or directly change it at the core of Ampache. Actually, I would go for fixing it in the core, but I don't know why it is implemented this way at the moment.

**Comment by Phyks** [comment]
An idea I have would be to:
* Keep only one album per physical album, in the database and store an associated total number of disks.
* For each album tracks, store the track number *and* the disk number in the tracks table.

That is move from
```
MariaDB [ampache]> DESCRIBE album;
+--------------+----------------------+------+-----+---------+----------------+
| Field        | Type                 | Null | Key | Default | Extra          |
+--------------+----------------------+------+-----+---------+----------------+
| id           | int(11) unsigned     | NO   | PRI | NULL    | auto_increment |
| name         | varchar(255)         | YES  | MUL | NULL    |                |
| prefix       | varchar(32)          | YES  |     | NULL    |                |
| mbid         | varchar(36)          | YES  |     | NULL    |                |
| year         | int(4) unsigned      | NO   | MUL | 1984    |                |
| disk         | smallint(5) unsigned | YES  | MUL | NULL    |                |
| mbid_group   | varchar(36)          | YES  |     | NULL    |                |
| release_type | varchar(32)          | YES  |     | NULL    |                |
| album_artist | int(11) unsigned     | YES  |     | NULL    |                |
+--------------+----------------------+------+-----+---------+----------------+
```
to
```
MariaDB [ampache]> DESCRIBE album;
+--------------+----------------------+------+-----+---------+----------------+
| Field        | Type                 | Null | Key | Default | Extra          |
+--------------+----------------------+------+-----+---------+----------------+
| id           | int(11) unsigned     | NO   | PRI | NULL    | auto_increment |
| name         | varchar(255)         | YES  | MUL | NULL    |                |
| prefix       | varchar(32)          | YES  |     | NULL    |                |
| mbid         | varchar(36)          | YES  |     | NULL    |                |
| year         | int(4) unsigned      | NO   | MUL | 1984    |                |
| nb_disks         | smallint(5) unsigned | YES  | MUL | NULL    |                |
| mbid_group   | varchar(36)          | YES  |     | NULL    |                |
| release_type | varchar(32)          | YES  |     | NULL    |                |
| album_artist | int(11) unsigned     | YES  |     | NULL    |                |
+--------------+----------------------+------+-----+---------+----------------+
```

(`disk` → `nb_disks` in `album` table)


And from
```
MariaDB [ampache]> DESCRIBE song;
+---------------+-------------------------+------+-----+---------+----------------+
| Field         | Type                    | Null | Key | Default | Extra          |
+---------------+-------------------------+------+-----+---------+----------------+
| id            | int(11) unsigned        | NO   | PRI | NULL    | auto_increment |
| file          | varchar(4096)           | YES  | MUL | NULL    |                |
| catalog       | int(11) unsigned        | NO   | MUL | 0       |                |
| album         | int(11) unsigned        | NO   | MUL | 0       |                |
| year          | mediumint(4) unsigned   | NO   |     | 0       |                |
| artist        | int(11) unsigned        | NO   | MUL | 0       |                |
| title         | varchar(255)            | YES  | MUL | NULL    |                |
| bitrate       | mediumint(8) unsigned   | NO   |     | 0       |                |
| rate          | mediumint(8) unsigned   | NO   |     | 0       |                |
| mode          | enum('abr','vbr','cbr') | YES  |     | NULL    |                |
| size          | int(11) unsigned        | NO   |     | 0       |                |
| time          | smallint(5) unsigned    | NO   |     | 0       |                |
| track         | smallint(5) unsigned    | YES  |     | NULL    |                |
| mbid          | varchar(36)             | YES  |     | NULL    |                |
| played        | tinyint(1) unsigned     | NO   | MUL | 0       |                |
| enabled       | tinyint(1) unsigned     | NO   | MUL | 1       |                |
| update_time   | int(11) unsigned        | YES  | MUL | 0       |                |
| addition_time | int(11) unsigned        | YES  | MUL | 0       |                |
| user_upload   | int(11)                 | YES  |     | NULL    |                |
| license       | int(11)                 | YES  |     | NULL    |                |
| composer      | varchar(256)            | YES  |     | NULL    |                |
| channels      | mediumint(9)            | YES  |     | NULL    |                |
+---------------+-------------------------+------+-----+---------+----------------+
```
to
```
MariaDB [ampache]> DESCRIBE song;
+---------------+-------------------------+------+-----+---------+----------------+
| Field         | Type                    | Null | Key | Default | Extra          |
+---------------+-------------------------+------+-----+---------+----------------+
| id            | int(11) unsigned        | NO   | PRI | NULL    | auto_increment |
| file          | varchar(4096)           | YES  | MUL | NULL    |                |
| catalog       | int(11) unsigned        | NO   | MUL | 0       |                |
| album         | int(11) unsigned        | NO   | MUL | 0       |                |
| year          | mediumint(4) unsigned   | NO   |     | 0       |                |
| artist        | int(11) unsigned        | NO   | MUL | 0       |                |
| title         | varchar(255)            | YES  | MUL | NULL    |                |
| bitrate       | mediumint(8) unsigned   | NO   |     | 0       |                |
| rate          | mediumint(8) unsigned   | NO   |     | 0       |                |
| mode          | enum('abr','vbr','cbr') | YES  |     | NULL    |                |
| size          | int(11) unsigned        | NO   |     | 0       |                |
| time          | smallint(5) unsigned    | NO   |     | 0       |                |
| track         | smallint(5) unsigned    | YES  |     | NULL    |                |
| disk         | smallint(5) unsigned    | YES  |     | NULL    |                |
| mbid          | varchar(36)             | YES  |     | NULL    |                |
| played        | tinyint(1) unsigned     | NO   | MUL | 0       |                |
| enabled       | tinyint(1) unsigned     | NO   | MUL | 1       |                |
| update_time   | int(11) unsigned        | YES  | MUL | 0       |                |
| addition_time | int(11) unsigned        | YES  | MUL | 0       |                |
| user_upload   | int(11)                 | YES  |     | NULL    |                |
| license       | int(11)                 | YES  |     | NULL    |                |
| composer      | varchar(256)            | YES  |     | NULL    |                |
| channels      | mediumint(9)            | YES  |     | NULL    |                |
+---------------+-------------------------+------+-----+---------+----------------+
```
(that is add a `disk` field)


This would solve basically everything I think. It would allow to group as we want, to return albums instead of "disks" in API calls and so on.

My only concern is:
Are there any albums with multiple disks and different names for each disk, that we would want to keep track of? With the actual solution, each disk is a kind of virtual album, which can have its own title. And deduplication is done on mbid. With the new scheme I suggest, all the disk are grouped together under a single title, the title of the album.

@ampache/developers Any thoughts on this?

**Comment by apastuszak** [comment]
There are quite a number of boxed sets of complete discographies.  The Musicbrainz tag <DISCSUBTITLE> is how I am currently handling it on my desktop, mostly because this is how Picard tags the album.

I have the boxed sets for The Beatles, Yes, and Rush, and it would be nice if each disc could have it's own title:  Album->Disc Name->Track
ie:  The Beatles in Mono->Magical Mystery Tour->Paperback Writer

**Comment by Phyks** [comment]
[Here](https://musicbrainz.org/release/84b998b5-d3a2-4bdb-a932-4642b0e4cc3a) is an example of such album with different titles for the CDs. Musicbrainz handles it well.

Ampache also handles it correctly at the moment:
![2016-08-03-151220](https://cloud.githubusercontent.com/assets/3856586/17366674/b5cd6328-598c-11e6-9f91-6f1b30198295.png)


With my suggestion in https://github.com/ampache/ampache/issues/1015#issuecomment-237211610, we will lose this possibility.

The only idea I have would be to add one extra level of indirection and add a `disks` table to store information about each disk in a multi-disk album.

Has anyone a better idea to fix this?

**Comment by apastuszak** [comment]
I am not a developer, just a tinkerer.  But I think you're right.  You'd need a separate table to store album name, disc number and disc name.

**Comment by apastuszak** [comment]
You might want to lump in my enhancement request into this issue also:

https://github.com/ampache/ampache/issues/687

**Comment by Phyks** [comment]
Sure, I think both issues are kind of dependent and can be tackled together. I am waiting for input from any other @ampache/developers on the solution I detailed above before considering implementing it, as it would require some major changes.

**Comment by apastuszak** [comment]
I assume this is something that's not going to happen any time soon, due to the major database changes.

**Comment by apastuszak** [comment]
If you look at the screenshots from:

https://github.com/ampache/ampache/issues/918

You'll see what a mess this can create.

A lot of new albums seem to have a "Deluxe" and regular release these days.  The "Deluxe" has a second disc with bonus tracks and live recordings.

**Comment by Afterster** [comment]
I agree on that, such logic should exists and an intermediate table is required if we want to do it properly.  Several SQL requests will be impacted by this changes.

**Comment by Phyks** [comment]
@apastuszak indeed. This has to be fixed. Not sure when it will be fixed, we were thinking about next milestones yesterday, this is to be planned somewhere. We have to define the major bugs to solve and the next steps for enhancement.

@Afterster ok for the logic.

Just to sum up (and brainstorm a bit on this), we would have
```
MariaDB [ampache]> DESCRIBE album;
+--------------+----------------------+------+-----+---------+----------------+
| Field        | Type                 | Null | Key | Default | Extra          |
+--------------+----------------------+------+-----+---------+----------------+
| id           | int(11) unsigned     | NO   | PRI | NULL    | auto_increment |
| name         | varchar(255)         | YES  | MUL | NULL    |                |
| prefix       | varchar(32)          | YES  |     | NULL    |                |
| mbid         | varchar(36)          | YES  |     | NULL    |                |
| year         | int(4) unsigned      | NO   | MUL | 1984    |                |
| mbid_group   | varchar(36)          | YES  |     | NULL    |                |
| release_type | varchar(32)          | YES  |     | NULL    |                |
| album_artist | int(11) unsigned     | YES  |     | NULL    |                |
+--------------+----------------------+------+-----+---------+----------------+

MariaDB [ampache]> DESCRIBE disk;
+---------------+-------------------------+------+-----+---------+----------------+
| Field         | Type                    | Null | Key | Default | Extra          |
+---------------+-------------------------+------+-----+---------+----------------+
| id            | int(11) unsigned        | NO   | PRI | NULL    | auto_increment |
| catalog       | int(11) unsigned        | NO   | MUL | 0       |                |
| album         | int(11) unsigned        | NO   | MUL | 0       |                |
| title         | varchar(255)            | YES  | MUL | NULL    |                |
+---------------+-------------------------+------+-----+---------+----------------+

MariaDB [ampache]> DESCRIBE song;
+---------------+-------------------------+------+-----+---------+----------------+
| Field         | Type                    | Null | Key | Default | Extra          |
+---------------+-------------------------+------+-----+---------+----------------+
| id            | int(11) unsigned        | NO   | PRI | NULL    | auto_increment |
| file          | varchar(4096)           | YES  | MUL | NULL    |                |
| catalog       | int(11) unsigned        | NO   | MUL | 0       |                |
| disk          | smallint(5) unsigned    | YES  |     | NULL    |                |
| year          | mediumint(4) unsigned   | NO   |     | 0       |                |
| artist        | int(11) unsigned        | NO   | MUL | 0       |                |
| title         | varchar(255)            | YES  | MUL | NULL    |                |
| bitrate       | mediumint(8) unsigned   | NO   |     | 0       |                |
| rate          | mediumint(8) unsigned   | NO   |     | 0       |                |
| mode          | enum('abr','vbr','cbr') | YES  |     | NULL    |                |
| size          | int(11) unsigned        | NO   |     | 0       |                |
| time          | smallint(5) unsigned    | NO   |     | 0       |                |
| track         | smallint(5) unsigned    | YES  |     | NULL    |                |
| mbid          | varchar(36)             | YES  |     | NULL    |                |
| played        | tinyint(1) unsigned     | NO   | MUL | 0       |                |
| enabled       | tinyint(1) unsigned     | NO   | MUL | 1       |                |
| update_time   | int(11) unsigned        | YES  | MUL | 0       |                |
| addition_time | int(11) unsigned        | YES  | MUL | 0       |                |
| user_upload   | int(11)                 | YES  |     | NULL    |                |
| license       | int(11)                 | YES  |     | NULL    |                |
| composer      | varchar(256)            | YES  |     | NULL    |                |
| channels      | mediumint(9)            | YES  |     | NULL    |                |
+---------------+-------------------------+------+-----+---------+----------------+
```

To sum up:
* `song` table references a `disk` rather than an `album` (`album` field is renamed to `disk`).
* `album` table loses its `disk` attribute (no more need to have the total number of disks in an album as it can be obtained from the `disk` table and it would be error prone to store it).
* A new `disk` table is introduced. A `disk` belongs to a `catalog` and references an `album` it is part of. It also has a `title` attribute.

This would require:
* Major rewrite of most of the SQL queries concerning `album` and `song` at the moment.
* Some rewrite in the APIs (XML and Subsonic) to reflect these changes.
* Fix the UI accordingly.

So it is kind of hard work.


This summary is mostly to keep a track of the possible solution to this issue (in case anyone is willing to contribute this) and also to check we are not forgetting anything. In particular, I would like to be sure I am not forgetting any interesting attribute on `disk`.

As per #687, it will be solved at the same time as `<DISCSUBTITLE>` will just be mapped to `disk.title` field.

**Comment by krodelabestiole** [comment]
indeed I think going trough a third table is mandatory.

one _track_ belongs to one _medium_ (might be vinyl, cd, tape, usb key or whatever) that belongs to one _release_.
a release can have many mediums, each one probably having many tracks.
so these are one-to-many relationships everywhere : I guess there is no need to worry if one track appears in many releases.

then yes, in a few specific cases it might be useful to name each medium (for classical music mostly).
@Phyks but I don't think it would be useful to have a "catalog" field for each medium/disk.

**Comment by apastuszak** [comment]
> 
> 
> I don't consider a collection of albums with each one having different titles as an "album". I usually label them as unique albums. eache with their own title and having only one disk.
> 
> I could see the Beatles "White Album" as one album with two disks, though.

I think what it really comes down to is how the end user tagged the files.  If a boxed set with multiple albums is tagged by the user with the "<ALBUM>" tag being The Beatles in Mono, then Ampache would obvioulsy respect that.

But there are boxed sets that are not individual albums, but each disc has it's own name.  For example, I own the boxed set "20 Years of Jethro Tull."(I'm showing my age here)  It contains 3 CDs:

- Disc 1 - Radio Archives and Rare Tracks
- Disc 2 - Flawed Gems and Other Sides of Tull
- Disc 3 - The Essential Tull

Though, not essential, displaying that information, if it exists, would be useful for the end user of the app.

Having that information displayed really is just a "nice to have."  Making sure an album that contains multiple CDs stays grouped together as single album really is a "have to have" feature, especially with all these "anniversary editions" coming out that contain as many as 5 CDs sometimes.

Was curious if this was on this list for 4.0.

**Comment by lachlan-00** [comment]
@apastuszak i've done some work on this when you enable the group disk option but i'm not finished yet.
![image](https://user-images.githubusercontent.com/1305249/58600866-a2084880-82c9-11e9-9714-a71e1dbab708.png)

I want to make sure that ALL the album row displays are grouped as well when this setting is enabled.

Right now this doesn't happen in the browse pages.
![image](https://user-images.githubusercontent.com/1305249/58600941-f57a9680-82c9-11e9-89c2-b838b8ca6ef6.png)

It looks like the browse pages ignore this until you get into the album list in the artist page. I consider this a bug when you've enabled the album_group option so it will be 'fixed' before 4.0.0 will release

**Comment by apastuszak** [comment]
This needs to be fixed in the Subsonic and XML API as well.

**Comment by lachlan-00** [comment]
I use Dsub all the time so i'll be looking at that too.

**Comment by apastuszak** [comment]
Ok, another thought here.  Are there any clients that use the native
Ampache XML API?  Would it be better to focus development on the Subsonic
API and deprecate the Ampache API?  Perhaps make a superset of the subsonic
API and convince existing clients to adopt it.

**Comment by lachlan-00** [comment]
Probably not going to be a good idea since subsonic went closed source. I'd rather keep both maintained and updated instead of relying on an unknown third party for support.

For me, the subsonic API is useful as the clients are generally better, but this is a symptom of the subsonic API being more mature and featureful compared to the XML API.

One of my goals is to match the subsonic api for features and work with the XML API client devs to make things they want part of the API. I've already reached out to a lot of the active developers for input and will be including some updates from their comments.

**Comment by apastuszak** [comment]
There are open source forks of Subsonic.  I'm running airsonic now.  There
is also supysonic, which is written in php.  Might be worth looking at
Supysonic.

**Comment by kuzi-moto** [comment]
Thanks @lachlan-00 for checking this out! One of my only gripes with Ampache.

**Comment by lachlan-00** [comment]
I have fixed this in my branch as long as you enable group multiple disks.
![image](https://user-images.githubusercontent.com/1305249/59172315-b6322c80-8b8a-11e9-99dd-85f084ed62e1.png)

This will come into the official core branch soon after i see if it breaks anything.

**Comment by apastuszak** [comment]
Does this with the Subsonic API also?

**Comment by lachlan-00** [comment]
Sure does @apastuszak I'm catching this at the build_cache part before you query albums.

I haven't tested it completely but it only shows a single album for me in a lot of areas. I think i have to change the search query slightly but hat's it.

**Comment by lachlan-00** [comment]
Sorry to double post it's actually just the search class. Just setting a reminder for myself to update album_to_sql to group as well.

Once i update this you'll have single disks in subsonic everywhere.

**Comment by lachlan-00** [comment]
Last thing to fix up is the search ui will still show the disk number.
![image](https://user-images.githubusercontent.com/1305249/59313406-2e683180-8cf4-11e9-8f08-fbf94971ca8e.png)

**Comment by apastuszak** [comment]
if I am on develop branch, should I see this change already?

**Comment by apastuszak** [comment]
> 
> 
> @apastuszak i've done some work on this when you enable the group disk option but i'm not finished yet.
> ![image](https://user-images.githubusercontent.com/1305249/58600866-a2084880-82c9-11e9-9714-a71e1dbab708.png)
> 
> I want to make sure that ALL the album row displays are grouped as well when this setting is enabled.
> 
> Right now this doesn't happen in the browse pages.
> ![image](https://user-images.githubusercontent.com/1305249/58600941-f57a9680-82c9-11e9-89c2-b838b8ca6ef6.png)
> 
> It looks like the browse pages ignore this until you get into the album list in the artist page. I consider this a bug when you've enabled the album_group option so it will be 'fixed' before 4.0.0 will release

This is odd.  I have never had this problem with the web UI.  It has always properly grouped multi-disk albums for me.

**Comment by lachlan-00** [comment]
Only core branch for now. The core branch is going to be deleted after it's merged with develop so I would stay on that branch.

Regarding the inconsistent grouping I found about 5+ situations where grouping was ignored or not implemented fully. So now the code looks for grouping before it gets to the UI.

The best part is that it's all done without modifying the backend beyond a few more query lines and if statements

**Comment by apastuszak** [comment]
Any estimate on how long till develop gets this?  I'm impatient.  I've been waiting for years for this to get fixed.

**Comment by lachlan-00** [comment]
Keep any eye on the modernization project.
https://github.com/ampache/ampache/projects/2

I'm still finding situations where grouping doesn't show things correctly. (Disks with a rating only show if the rating is on that disk) but I'm pretty happy with the state of things.

The last major things to test are installing from scratch then running through a test plan.

One I'm happy that the core branch is better quality than develop without introducing new bugs I'll merge it.

**Comment by lachlan-00** [comment]
I'll be testing fresh installs at home this weekend so it's actually been faster to complete this than I thought it would be

**Comment by kuzi-moto** [comment]
Is it a good idea to start using the core branch to test?

**Comment by lachlan-00** [comment]
I'm wary of saying yes as for the last week i've been fixing bugs i introduced. But i will say that i think it's really really close to moving over.

If you can wait the weekend i'll add options in the config file to force a branch for updates.
That way when core gets deleted all you should need to do is change your branch to develop again.

**Comment by lachlan-00** [comment]
Update for you all. I've got some little bugs in grouping to fix but then I'm done.

Ratings need to be set/unset across each disk and there are some UI issues with the grouping that allows me to click clear when it's not my rating. (it doesn't affect the other users rating but it should remain on screen as i haven't set my own rating.)

Once these are fixed I'll be starting my test plan and working on the migration to develop.

**Comment by lachlan-00** [comment]
Guess what? This is ready to close.

If you're willing to test it out, the core branch has complete grouping now. All you need to do is enable group multiple disks in the settings page.

Fixed and tested in the following sections.
* UI, API, Subsonic, Ratings, Flags, Stats, Random, Search. 

For those who want to wait for develop/master; the core branch is feature complete and will be merged into develop once I've finished testing.

**Comment by apastuszak** [comment]
Just did a hit pull on develop and I’m not seeing the option. 

Andy

**Comment by lachlan-00** [comment]
pulled to the wrong branch, changes are incoming on
https://github.com/ampache/ampache/pull/1931

**Comment by apastuszak** [comment]
Ok, updated to the latest develop with a git pull and I'm still not seeing multi-disc albums grouped in my subsonic clients.  What am I doing wrong here?

**Comment by lachlan-00** [comment]
All you need to do is enable "Album - Group multiple disks" The group settings check for this and run the different queries.
![image](https://user-images.githubusercontent.com/1305249/59892145-50ac2e80-941b-11e9-84ba-7519a9146c42.png)

If you've set it another issue might be that you need to clear the albums cache in ampache debug.
![Uploading image.png…]()

**Comment by apastuszak** [comment]
Those settings are in a different location for me:

[https://i.imgur.com/zedN8Tg.png](url)

**Comment by lachlan-00** [comment]
That's odd, your DB doesn't have the same preference rows as me.  When they're at the top it means hey don't have a category in the table.

Mine have the library category so they get grouped further down.
![image](https://user-images.githubusercontent.com/1305249/59892573-f7dd9580-941c-11e9-9ed3-438a6401e9b9.png)

**Comment by apastuszak** [comment]
My copy is at least 5 years old at this point.  I've jjust been updating with git pulls.  Maybe I should just reinstall a fresh copy with a new database?

**Comment by lachlan-00** [comment]
The preferences were inserted in 2015 from what i can see. (line 691)
https://github.com/ampache/ampache/blame/develop/sql/ampache.sql

But there is no reason why it shouldn't work; the subcategory is only for visual representation so maybe you've got other things missing from it? I've been using my DB for easily as long so i wouldn't blow it away and lose all that data.

**Comment by apastuszak** [comment]
I just installed a fresh copy alongside my existing copy.  I have ALL SORTS of extra options my other copy doesn't have.  Rescanning my library now.  Hopefully this will fix it.  I've been waiting for this feature for years.

**Comment by lachlan-00** [comment]
it would be good if you could compare your preference table between the 2 versions.

I'm writing a DB update for the subcategory now but it would be good to know what's missing for you so i can update that as well

**Comment by apastuszak** [comment]
Tell me how to do it, and I can probably do it in the morning.  Screen shots from phpMyAdmin OK, or do you need more than that.

**Comment by lachlan-00** [comment]
This query is all i need. check what preferences are in the new install that are missing in the old one.
```
SELECT * FROM `AMPACHENEW`.`preference` WHERE `name` not in (SELECT `name` from `AMPACHEOLD`.`preference`);
SELECT * FROM `AMPACHENEW`.`user_preference` WHERE `preference` not in (SELECT `preference` from `AMPACHEOLD`.`user_preference`);
```

**Comment by stebe** [comment]
I've been using Ampache since 3.4 and I am also missing a lot of subcategories in preferences and maybe options. I think I'll create a new database and compare all tables, maybe something is missing elsewhere.

**Comment by lachlan-00** [comment]
That would be great! Anything that can show a difference will help. I'd rather be able to upgrade you on the same db than redo it.

The subcategories aren't critical to operation but there must be other database settings you're missing.

**Comment by apastuszak** [comment]
Ok, here is what I got from those two queries:

![sql1](https://user-images.githubusercontent.com/3401054/59923271-0ae26c80-9401-11e9-8cab-3503a08b01dc.png)
![sql2](https://user-images.githubusercontent.com/3401054/59923272-0ae26c80-9401-11e9-8580-ed01053fe8ac.png)

**Comment by apastuszak** [comment]
My discs still are not grouping:

![album settings](https://user-images.githubusercontent.com/3401054/59923392-53018f00-9401-11e9-8810-81b283c08bf3.png)
![AlQayo6](https://user-images.githubusercontent.com/3401054/59923394-5563e900-9401-11e9-87fb-c01dbb9efd65.jpg)

**Comment by apastuszak** [comment]
This app is Play:Sub on iOS.  I uninstalled the app and reinstalled it just to get a a fresh setup.

**Comment by apastuszak** [comment]
Screenshot from AVSub on iOS

<img width="414" alt="PNG image" src="https://user-images.githubusercontent.com/3401054/59924002-b8a24b00-9402-11e9-8c3e-d8d036dc98a9.png">

**Comment by stebe** [comment]
I did a quick check and both the category and subcategory columns do not match in the preferences table between a new install and my old database.  The number of rows also don't match but this may be because I've not enabled some options/plugins on the test database.

```
 SELECT * FROM `ampache-test`.`preference` WHERE `name` not in (SELECT `name` from `ampache`.`preference`);
+----+------------------+-------+---------------------------+-------+---------+----------+-------------+
| id | name             | value | description               | level | type    | catagory | subcatagory |
+----+------------------+-------+---------------------------+-------+---------+----------+-------------+
| 71 | httpq_active     | 0     | HTTPQ Active Instance     |    25 | integer | internal | httpq       |
| 72 | shoutcast_active | 0     | Shoutcast Active Instance |    25 | integer | internal | shoutcast   |
+----+------------------+-------+---------------------------+-------+---------+----------+-------------+

SELECT * FROM `ampache-test`.`user_preference` WHERE `preference` not in (SELECT `preference` from `ampache`.`user_preference`);
+------+------------+------------------------------------------+
| user | preference | value                                    |
+------+------------+------------------------------------------+
|   -1 |         25 | 80                                       |
|   -1 |         34 | 27                                       |
|   -1 |         35 | 27                                       |
|   -1 |         36 | 27                                       |
|   -1 |         49 | 1                                        |
|   -1 |         57 |                                          |
|   -1 |         70 | 0                                        |
|   -1 |         71 | 0                                        |
|   -1 |         72 | 0                                        |
|   -1 |         77 |                                          |
|   -1 |         78 |                                          |
|   -1 |        110 | 0                                        |
|   -1 |        104 | 0                                        |
|   -1 |        103 | 7                                        |
|   -1 |        102 | 0                                        |
|   -1 |        101 | 1                                        |
|   -1 |        100 | 1                                        |
|   -1 |         99 | 0                                        |
|   -1 |         95 | 1                                        |
|   -1 |         93 | 1                                        |
|   -1 |         92 | 1                                        |
|   -1 |         91 | 1                                        |
|   -1 |         90 | 1                                        |
|   -1 |         89 | 1                                        |
|   -1 |         88 | 1                                        |
|   -1 |         86 | 1                                        |
|   -1 |         85 | 1                                        |
|   -1 |         84 | 0                                        |
|   -1 |         83 | 0                                        |
|   -1 |         79 | 50                                       |
|   -1 |         80 | 50                                       |
|   -1 |         82 | 1                                        |
|   -1 |         81 | 1                                        |
|   -1 |        117 | 1                                        |
|   -1 |        118 | 0                                        |
|   -1 |        119 |                                          |
|   -1 |        120 | 1                                        |
|   -1 |        121 | 0                                        |
|   -1 |        122 | 1                                        |
|   -1 |        123 | 1                                        |
|   -1 |        124 | 0                                        |
|   -1 |        125 | 1                                        |
|   -1 |        126 | 1                                        |
|   -1 |        127 | 1                                        |
|   -1 |        128 | 1                                        |
|   -1 |        129 |                                          |
|   -1 |        130 | album,ep,live,single                     |
|   -1 |        131 | 1                                        |
|   -1 |        132 | 10                                       |
|   -1 |        133 | 0                                        |
|   -1 |        134 | 1                                        |
|   -1 |        135 | 1                                        |
|   -1 |        136 |                                          |
|   -1 |         96 |                                          |
|   -1 |         97 |                                          |
|   -1 |         98 |                                          |
|    1 |         70 | 0                                        |
|    1 |         71 | 0                                        |
|    1 |         72 | 0                                        |
|    1 |         77 |                                          |
|    1 |         78 |                                          |
|    1 |        102 | 0                                        |
|    1 |        123 | 1                                        |
|    1 |         82 | 1                                        |
|    1 |         83 | 0                                        |
|    1 |         84 | 0                                        |
|    1 |         85 | 1                                        |
|    1 |         88 | 1                                        |
|    1 |         89 | 1                                        |
|    1 |         90 | 1                                        |
|    1 |         91 | 1                                        |
|    1 |         92 | 1                                        |
|    1 |         93 | 1                                        |
|    1 |         96 | 1561115167                               |
|    1 |         97 | eb7e12fd504e77c6cd |
|    1 |         98 |                                          |
|    1 |         99 | 0                                        |
|    1 |        100 | 1                                        |
|    1 |        101 | 1                                        |
|    1 |        104 | 0                                        |
|    1 |        110 | 0                                        |
|    1 |        121 | 0                                        |
|    1 |        122 | 1                                        |
|    1 |        124 | 0                                        |
|    1 |        125 | 1                                        |
|    1 |        126 | 1                                        |
|    1 |        127 | 1                                        |
|    1 |        128 | 1                                        |
|    1 |        129 |                                          |
|    1 |        130 | album,ep,live,single                     |
|    1 |        131 | 1                                        |
|    1 |        132 | 10                                       |
|    1 |        133 | 0                                        |
|    1 |        134 | 1                                        |
|    1 |        136 |                                          |
|   -1 |        149 | 1                                        |
|   -1 |        150 | 0                                        |
|   -1 |        151 |                                          |
|   -1 |        152 |                                          |
|   -1 |        153 |                                          |
|    1 |        149 | 1                                        |
|    1 |        150 | 0                                        |
|    1 |        151 |                                          |
|    1 |        152 |                                          |
|    1 |        153 |                                          |
+------+------------+------------------------------------------+
105 rows in set (0.002 sec)
```
```
[ampache-test]> select name,catagory,subcatagory from preference;
+---------------------------------------+-----------+--------------+
| name                                  | catagory  | subcatagory  |
+---------------------------------------+-----------+--------------+
| download                              | options   | feature      |
| popular_threshold                     | interface | query        |
| transcode_bitrate                     | streaming | transcoding  |
| site_title                            | interface | custom       |
| lock_songs                            | system    | NULL         |
| force_http_play                       | system    | NULL         |
| play_type                             | streaming | NULL         |
| lang                                  | interface | NULL         |
| playlist_type                         | playlist  | NULL         |
| theme_name                            | interface | theme        |
| localplay_level                       | options   | localplay    |
| localplay_controller                  | options   | localplay    |
| allow_stream_playback                 | options   | feature      |
| allow_democratic_playback             | options   | feature      |
| allow_localplay_playback              | options   | localplay    |
| stats_threshold                       | interface | query        |
| offset_limit                          | interface | query        |
| rate_limit                            | streaming | transcoding  |
| playlist_method                       | playlist  | NULL         |
| transcode                             | streaming | transcoding  |
| show_lyrics                           | interface | player       |
| mpd_active                            | internal  | mpd          |
| httpq_active                          | internal  | httpq        |
| shoutcast_active                      | internal  | shoutcast    |
| lastfm_grant_link                     | internal  | lastfm       |
| lastfm_challenge                      | internal  | lastfm       |
| now_playing_per_user                  | interface | home         |
| album_sort                            | interface | library      |
| show_played_times                     | interface | library      |
| song_page_title                       | interface | player       |
| subsonic_backend                      | system    | backend      |
| webplayer_flash                       | streaming | player       |
| webplayer_html5                       | streaming | player       |
| allow_personal_info_now               | interface | privacy      |
| allow_personal_info_recent            | interface | privacy      |
| allow_personal_info_time              | interface | privacy      |
| allow_personal_info_agent             | interface | privacy      |
| ui_fixed                              | interface | theme        |
| autoupdate                            | system    | update       |
| autoupdate_lastcheck                  | internal  | update       |
| autoupdate_lastversion                | internal  | update       |
| autoupdate_lastversion_new            | internal  | update       |
| webplayer_confirmclose                | interface | player       |
| webplayer_pausetabs                   | interface | player       |
| stream_beautiful_url                  | streaming | NULL         |
| share                                 | options   | feature      |
| share_expire                          | system    | share        |
| slideshow_time                        | interface | player       |
| broadcast_by_default                  | streaming | player       |
| concerts_limit_future                 | interface | query        |
| concerts_limit_past                   | interface | query        |
| album_group                           | interface | library      |
| topmenu                               | interface | theme        |
| demo_clear_sessions                   | playlist  | NULL         |
| show_donate                           | interface | NULL         |
| upload_catalog                        | system    | upload       |
| allow_upload                          | system    | upload       |
| upload_subdir                         | system    | upload       |
| upload_user_artist                    | system    | upload       |
| upload_script                         | system    | upload       |
| upload_allow_edit                     | system    | upload       |
| daap_backend                          | system    | backend      |
| daap_pass                             | system    | backend      |
| upnp_backend                          | system    | backend      |
| allow_video                           | options   | feature      |
| album_release_type                    | interface | library      |
| ajax_load                             | interface | NULL         |
| direct_play_limit                     | interface | player       |
| home_moment_albums                    | interface | home         |
| home_moment_videos                    | interface | home         |
| home_recently_played                  | interface | home         |
| home_now_playing                      | interface | home         |
| custom_logo                           | interface | custom       |
| album_release_type_sort               | interface | library      |
| browser_notify                        | interface | notification |
| browser_notify_timeout                | interface | notification |
| geolocation                           | options   | feature      |
| webplayer_aurora                      | streaming | player       |
| upload_allow_remove                   | system    | upload       |
| custom_login_logo                     | interface | custom       |
| custom_favicon                        | interface | custom       |
| custom_text_footer                    | interface | custom       |
| webdav_backend                        | system    | backend      |
| notify_email                          | options   | NULL         |
| theme_color                           | interface | theme        |
| disabled_custom_metadata_fields       | system    | metadata     |
| disabled_custom_metadata_fields_input | system    | metadata     |
| podcast_keep                          | system    | podcast      |
| podcast_new_download                  | system    | podcast      |
| libitem_contextmenu                   | interface | library      |
| upload_catalog_pattern                | system    | upload       |
| catalog_check_duplicate               | system    | catalog      |
| browse_filter                         | interface | library      |
| sidebar_light                         | interface | theme        |
| custom_blankalbum                     | interface | custom       |
| custom_blankmovie                     | interface | custom       |
| libitem_browse_alpha                  | interface | library      |
+---------------------------------------+-----------+--------------+
97 rows in set (0.001 sec)
```
```

[ampache]> select name,catagory,subcatagory from preference;
+---------------------------------------+-----------+-------------+
| name                                  | catagory  | subcatagory |
+---------------------------------------+-----------+-------------+
| download                              | options   | feature     |
| popular_threshold                     | interface | query       |
| transcode_bitrate                     | streaming | transcoding |
| site_title                            | system    | custom      |
| lock_songs                            | system    | NULL        |
| force_http_play                       | system    | NULL        |
| play_type                             | streaming | NULL        |
| lang                                  | interface | NULL        |
| playlist_type                         | playlist  | NULL        |
| theme_name                            | interface | theme       |
| localplay_level                       | options   | localplay   |
| localplay_controller                  | options   | localplay   |
| allow_stream_playback                 | options   | feature     |
| allow_democratic_playback             | options   | feature     |
| allow_localplay_playback              | options   | localplay   |
| stats_threshold                       | interface | query       |
| offset_limit                          | interface | query       |
| rate_limit                            | streaming | transcoding |
| playlist_method                       | playlist  | NULL        |
| transcode                             | streaming | NULL        |
| show_lyrics                           | interface | player      |
| mpd_active                            | internal  | mpd         |
| now_playing_per_user                  | interface | home        |
| album_sort                            | interface | library     |
| show_played_times                     | interface | library     |
| song_page_title                       | interface | player      |
| subsonic_backend                      | system    | backend     |
| webplayer_flash                       | streaming | player      |
| webplayer_html5                       | streaming | player      |
| allow_personal_info_now               | interface | privacy     |
| allow_personal_info_recent            | interface | privacy     |
| allow_personal_info_time              | interface | privacy     |
| allow_personal_info_agent             | interface | privacy     |
| ui_fixed                              | interface | theme       |
| autoupdate                            | system    | update      |
| autoupdate_lastcheck                  | internal  | update      |
| autoupdate_lastversion                | internal  | update      |
| autoupdate_lastversion_new            | internal  | update      |
| webplayer_confirmclose                | interface | player      |
| webplayer_pausetabs                   | interface | NULL        |
| stream_beautiful_url                  | streaming | NULL        |
| share                                 | options   | feature     |
| share_expire                          | system    | share       |
| slideshow_time                        | interface | player      |
| broadcast_by_default                  | streaming | player      |
| concerts_limit_future                 | interface | query       |
| concerts_limit_past                   | interface | query       |
| album_group                           | interface | library     |
| topmenu                               | interface | theme       |
| topmenu                               | interface | NULL        |
| topmenu                               | interface | NULL        |
| demo_clear_sessions                   | playlist  | NULL        |
| show_donate                           | interface | NULL        |
| upload_catalog                        | system    | upload      |
| allow_upload                          | system    | upload      |
| upload_subdir                         | system    | upload      |
| upload_user_artist                    | system    | upload      |
| upload_script                         | system    | upload      |
| upload_allow_edit                     | system    | upload      |
| daap_backend                          | system    | backend     |
| daap_pass                             | system    | backend     |
| upnp_backend                          | system    | backend     |
| allow_video                           | options   | feature     |
| album_release_type                    | interface | NULL        |
| ajax_load                             | interface | NULL        |
| direct_play_limit                     | interface | NULL        |
| home_moment_albums                    | interface | NULL        |
| home_moment_videos                    | interface | NULL        |
| home_recently_played                  | interface | NULL        |
| home_now_playing                      | interface | NULL        |
| custom_logo                           | interface | NULL        |
| album_release_type_sort               | interface | NULL        |
| browser_notify                        | interface | NULL        |
| browser_notify_timeout                | interface | NULL        |
| geolocation                           | options   | NULL        |
| webplayer_aurora                      | streaming | NULL        |
| xbmc_active                           | internal  | NULL        |
| vlc_active                            | internal  | NULL        |
| upload_allow_remove                   | system    | NULL        |
| custom_login_logo                     | interface | NULL        |
| custom_favicon                        | interface | NULL        |
| custom_text_footer                    | interface | NULL        |
| webdav_backend                        | system    | NULL        |
| notify_email                          | options   | NULL        |
| catalogfav_columns                    | plugins   | NULL        |
| theme_color                           | interface | NULL        |
| disabled_custom_metadata_fields       | system    | NULL        |
| disabled_custom_metadata_fields_input | system    | NULL        |
| amazon_base_url                       | plugins   | NULL        |
| amazon_max_results_pages              | plugins   | NULL        |
| amazon_developer_public_key           | plugins   | NULL        |
| amazon_developer_private_api_key      | plugins   | NULL        |
| amazon_developer_associate_tag        | plugins   | NULL        |
| hm_message                            | plugins   | NULL        |
| hm_level                              | plugins   | NULL        |
| tvdb_api_key                          | plugins   | NULL        |
| tmdb_api_key                          | plugins   | NULL        |
| podcast_keep                          | system    | NULL        |
| podcast_new_download                  | system    | NULL        |
| libitem_contextmenu                   | interface | library     |
| upload_catalog_pattern                | system    | upload      |
| catalog_check_duplicate               | system    | catalog     |
| browse_filter                         | interface | library     |
| sidebar_light                         | interface | theme       |
| custom_blankalbum                     | interface | custom      |
| custom_blankmovie                     | interface | custom      |
| libitem_browse_alpha                  | interface | library     |
| lastfm_challenge                      | internal  | lastfm      |
| lastfm_grant_link                     | plugins   | lastfm      |
| tadb_api_key                          | plugins   | theaudiodb  |
| discogs_api_key                       | plugins   | discogs     |
| discogs_secret_api_key                | plugins   | discogs     |
| librefm_challenge                     | internal  | libre.fm    |
| librefm_grant_link                    | plugins   | libre.fm    |
+---------------------------------------+-----------+-------------+
114 rows in set (0.001 sec)

```

**Comment by lachlan-00** [comment]
@apastuszak I'll look up those numbers and see what's missing and check out this iOS app.

**Comment by apastuszak** [comment]
My library was mostly FLAC files.  I have a separate folder with all the
files converted to MP3/M4A.  I deleted my library and am importing the
lossy compressed files to see if that makes a difference.  If it does not,
then I'll put the FLACs back in and can give you an account on my server.
I have an Android tablet with DSub on it.  I'll test on that too.

I am also browsing my ID3 tages and not folders.  Don't know if that makes
a difference,

epo

**Comment by lachlan-00** [comment]
I use dsub successfully it might be the id3tag browse? I've never set that before and the tag queries are all database tags so they might ignore something.

I'll set tag browse now and see if that breaks it

**Comment by lachlan-00** [comment]
That's it!

I enabled browse by id3 in ultrasonic and they split!

**Comment by apastuszak** [comment]
Oh man!  I was really hoping it was somethingI was doing wrong....

**Comment by lachlan-00** [comment]
I'll need to work out what that does. It's a subsonic specific method so at least all I need to do is alter that API call.

**Comment by apastuszak** [comment]
I have some notes from the AVSub developer.  I'll pass them along.

**Comment by apastuszak** [comment]
Check out:

https://github.com/ampache/ampache/issues/918

Hopefully that has some useful information in it.

**Comment by lachlan-00** [comment]
Looks simple enough. Id3 search is just using a different browse method so I just need to double check that.
For the preferences I'll be looking at that tonight too so hopefully should be done then
```
File structure vs ID3 tags

Starting with version 1.8.0, the API provides methods for accessing the media collection organized according to ID3 tags, rather than file structure. 
For instance, browsing through the collection using ID3 tags should use the getArtists, getArtist and getAlbum methods. To browse using file structure you would use getIndexes and getMusicDirectory. 
```

**Comment by lachlan-00** [comment]
Here's the short answer
* getMusicDirectory - function used when id3 is disabled and grouping works correctly.
* getArtist, getAlbum - function used when id3 is enabled and grouping doesn't work.

Long answer
getAlbum is returning individual groups including the [disk 2] part of the strings so it's definitely ignoring all the code changes. The issue is inside the subsonic_* classes in ampache so avsub/etc can't change anything to fix it.

The good news is that setting doesn't need to be set for Ampache as it requires id3 data to even function so this setting is actually a bit redundant. Disabling that setting shouldn't have any functional difference in the app as far as i can see when using ampache.

The other good news is that this can be fixed, it's just harder to to than rewriting queries as the subsonic api in ampache uses the id's as literal albums right now.

**Comment by apastuszak** [comment]
OK, something odd is happening here, and I don't know if I need to re-open this.  I just fired up AVSub (an iOS Subsonic client) and turned off browsing by ID3 tag and told it to browse by folder.  Here is what I am seeing when I get a list of albums:

![Um2oQC0](https://user-images.githubusercontent.com/3401054/60852867-8e54d980-a1c7-11e9-8a20-61c2ffbf18f3.png)

Station to Station has 4 CDs in it.  When I go into Station to Station (or any other album), it only shows me the LAST disc of the set:

![RvxY2GL](https://user-images.githubusercontent.com/3401054/60852905-b2b0b600-a1c7-11e9-9dcc-c9290bdb5336.png)

If I turn on browsing by ID3 tags, then the discs separate into multiple albums.

**Comment by lachlan-00** [comment]
I'll follow up in the new issue but this seems to be option/avsub specific.
