### ISSUE TITLE
KODI local play no playback

### ISSUE THREAD

**Issue by OpsCharlie** [ampache/ampache#1030]
When I want to push a song/playlist to KODI, it doens't play.
When a song is playing, I can stop it.

KODI: 15.2 (openelec 6) 
AMPACE: Ampache 3.8.1-develop 

LOG FILE:

```
2015-11-30 14:06:17 [admin] (ajax.server.php) -> Called for page: {localplay}
2015-11-30 14:06:17 [admin] (xbmc) -> Trying to connect xbmc instance 192.168.1.202:80.
2015-11-30 14:06:18 [admin] (xbmc) -> Connected.
2015-11-30 14:06:18 [admin] (xbmc) -> play failed: Failed to execute method.
2015-11-30 14:06:18 [admin] (localplay) -> Error Unable to start playback, check xbmc controller
```

**Comment by Afterster** [comment]
Indeed after testing, this looks to be broken... It could come from latest changes on Ampache or latest changes on Kodi, debug will be required.
I'm not using Kodi anymore and I know there was a few people with development skill that was using it. Would be great to have official maintainers for several plugins, this would help a lot.
Anyone willing to maintain it? @Jucgshu @titoko?

**Comment by nakinigit** [comment]
This is possibly the same problem I am seeing. I send music to KODI via local play, does not automatically play. But if I sit in front of KODI and view the playlists, I see the playlist was sent from Ampache, and I have to manually select it in KODI in order to play it.

I agree, not sure if its kodi or something broke in ampache. Used to work fine during the xbmc days.

**Comment by Afterster** [comment]
Looks like Kodi is sending a HEAD request to play the file but then fail to process it without any information on logs.
Wanting for some help on this, thanks.

**Comment by Phyks** [comment]
@Charlietje @nakinigit @Afterster Anyone can do a tcpdump of what is going on? (especially about this HEAD request which is done)

I tried to setup a Kodi on my machine to debug it, but it failed terribly bad, and I cannot run Kodi at all. :/

**Comment by nakinigit** [comment]
Don't know much about tcpdump, but here is a snippet. Let me know if you need something specific.

`18:15:10.902100 IP (tos 0x0, ttl 64, id 34514, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [S], cksum 0xca4c (incorrect -> 0x2875), seq 31901608, win 29200, options [mss 1460,sackOK,TS val 288178554 ecr 0,nop,wscale 7], length 0
	0x0000:  4500 003c 86d2 4000 4006 e9cb c0a8 2468  E..<..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c7a8 0000 0000  ..$e...P........
	0x0020:  a002 7210 ca4c 0000 0204 05b4 0402 080a  ..r..L..........
	0x0030:  112d 417a 0000 0000 0103 0307            .-Az........
18:15:10.902516 IP (tos 0x0, ttl 64, id 34515, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xf332), seq 31901609, ack 241416782, win 229, options [nop,nop,TS val 288178554 ecr 396402], length 0
	0x0000:  4500 0034 86d3 4000 4006 e9d2 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c7a9 0e63 ba4e  ..$e...P.....c.N
	0x0020:  8010 00e5 ca44 0000 0101 080a 112d 417a  .....D.......-Az
	0x0030:  0006 0c72                                ...r
18:15:10.902541 IP (tos 0x0, ttl 64, id 34516, offset 0, flags [DF], proto TCP (6), length 147)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [P.], cksum 0xcaa3 (incorrect -> 0x6d84), seq 31901609:31901704, ack 241416782, win 229, options [nop,nop,TS val 288178554 ecr 396402], length 95
	0x0000:  4500 0093 86d4 4000 4006 e972 c0a8 2468  E.....@.@..r..$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c7a9 0e63 ba4e  ..$e...P.....c.N
	0x0020:  8018 00e5 caa3 0000 0101 080a 112d 417a  .............-Az
	0x0030:  0006 0c72 4745 5420 2f6a 736f 6e72 7063  ...rGET./jsonrpc
	0x0040:  2048 5454 502f 312e 310d 0a41 7574 686f  .HTTP/1.1..Autho
	0x0050:  7269 7a61 7469 6f6e 3a20 4261 7369 6320  rization:.Basic.
	0x0060:  6233 4e74 597a 7076 6332 316a 0d0a 486f  b3NtYzpvc21j..Ho
	0x0070:  7374 3a20 3139 322e 3136 382e 3336 2e31  st:.192.168.36.1
	0x0080:  3031 0d0a 4163 6365 7074 3a20 2a2f 2a0d  01..Accept:.*/*.
	0x0090:  0a0d 0a                                  ...
18:15:11.027036 IP (tos 0x0, ttl 64, id 34517, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xece9), seq 31901704, ack 241418230, win 251, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86d5 4000 4006 e9d0 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 bff6  ..$e...P.....c..
	0x0020:  8010 00fb ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.027150 IP (tos 0x0, ttl 64, id 34518, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xe72a), seq 31901704, ack 241419678, win 274, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86d6 4000 4006 e9cf c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 c59e  ..$e...P.....c..
	0x0020:  8010 0112 ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.027260 IP (tos 0x0, ttl 64, id 34519, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xe16c), seq 31901704, ack 241421126, win 296, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86d7 4000 4006 e9ce c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 cb46  ..$e...P.....c.F
	0x0020:  8010 0128 ca44 0000 0101 080a 112d 419a  ...(.D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.027383 IP (tos 0x0, ttl 64, id 34520, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xdbad), seq 31901704, ack 241422574, win 319, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86d8 4000 4006 e9cd c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 d0ee  ..$e...P.....c..
	0x0020:  8010 013f ca44 0000 0101 080a 112d 419a  ...?.D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.027511 IP (tos 0x0, ttl 64, id 34521, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xd5ee), seq 31901704, ack 241424022, win 342, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86d9 4000 4006 e9cc c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 d696  ..$e...P.....c..
	0x0020:  8010 0156 ca44 0000 0101 080a 112d 419a  ...V.D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.027629 IP (tos 0x0, ttl 64, id 34522, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xd030), seq 31901704, ack 241425470, win 364, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86da 4000 4006 e9cb c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 dc3e  ..$e...P.....c.>
	0x0020:  8010 016c ca44 0000 0101 080a 112d 419a  ...l.D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.027752 IP (tos 0x0, ttl 64, id 34523, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xca71), seq 31901704, ack 241426918, win 387, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86db 4000 4006 e9ca c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 e1e6  ..$e...P.....c..
	0x0020:  8010 0183 ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.027875 IP (tos 0x0, ttl 64, id 34524, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xc4b2), seq 31901704, ack 241428366, win 410, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86dc 4000 4006 e9c9 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 e78e  ..$e...P.....c..
	0x0020:  8010 019a ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.027998 IP (tos 0x0, ttl 64, id 34525, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xbef4), seq 31901704, ack 241429814, win 432, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86dd 4000 4006 e9c8 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 ed36  ..$e...P.....c.6
	0x0020:  8010 01b0 ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.028121 IP (tos 0x0, ttl 64, id 34526, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xb935), seq 31901704, ack 241431262, win 455, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86de 4000 4006 e9c7 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 f2de  ..$e...P.....c..
	0x0020:  8010 01c7 ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.028248 IP (tos 0x0, ttl 64, id 34527, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xb377), seq 31901704, ack 241432710, win 477, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86df 4000 4006 e9c6 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 f886  ..$e...P.....c..
	0x0020:  8010 01dd ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.028367 IP (tos 0x0, ttl 64, id 34528, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xadb8), seq 31901704, ack 241434158, win 500, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86e0 4000 4006 e9c5 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e63 fe2e  ..$e...P.....c..
	0x0020:  8010 01f4 ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.028490 IP (tos 0x0, ttl 64, id 34529, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xa7f9), seq 31901704, ack 241435606, win 523, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86e1 4000 4006 e9c4 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 03d6  ..$e...P.....d..
	0x0020:  8010 020b ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.028618 IP (tos 0x0, ttl 64, id 34530, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0xa23b), seq 31901704, ack 241437054, win 545, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86e2 4000 4006 e9c3 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 097e  ..$e...P.....d.~
	0x0020:  8010 0221 ca44 0000 0101 080a 112d 419a  ...!.D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.028736 IP (tos 0x0, ttl 64, id 34531, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x9c7c), seq 31901704, ack 241438502, win 568, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86e3 4000 4006 e9c2 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 0f26  ..$e...P.....d.&
	0x0020:  8010 0238 ca44 0000 0101 080a 112d 419a  ...8.D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.028860 IP (tos 0x0, ttl 64, id 34532, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x96bd), seq 31901704, ack 241439950, win 591, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86e4 4000 4006 e9c1 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 14ce  ..$e...P.....d..
	0x0020:  8010 024f ca44 0000 0101 080a 112d 419a  ...O.D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.028987 IP (tos 0x0, ttl 64, id 34533, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x90ff), seq 31901704, ack 241441398, win 613, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86e5 4000 4006 e9c0 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 1a76  ..$e...P.....d.v
	0x0020:  8010 0265 ca44 0000 0101 080a 112d 419a  ...e.D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.029105 IP (tos 0x0, ttl 64, id 34534, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x8b40), seq 31901704, ack 241442846, win 636, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86e6 4000 4006 e9bf c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 201e  ..$e...P.....d..
	0x0020:  8010 027c ca44 0000 0101 080a 112d 419a  ...|.D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.029228 IP (tos 0x0, ttl 64, id 34535, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x8582), seq 31901704, ack 241444294, win 658, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86e7 4000 4006 e9be c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 25c6  ..$e...P.....d%.
	0x0020:  8010 0292 ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.029356 IP (tos 0x0, ttl 64, id 34536, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x7fc3), seq 31901704, ack 241445742, win 681, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86e8 4000 4006 e9bd c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 2b6e  ..$e...P.....d+n
	0x0020:  8010 02a9 ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.029474 IP (tos 0x0, ttl 64, id 34537, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x7a04), seq 31901704, ack 241447190, win 704, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86e9 4000 4006 e9bc c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 3116  ..$e...P.....d1.
	0x0020:  8010 02c0 ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.029599 IP (tos 0x0, ttl 64, id 34538, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x7446), seq 31901704, ack 241448638, win 726, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86ea 4000 4006 e9bb c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 36be  ..$e...P.....d6.
	0x0020:  8010 02d6 ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.029722 IP (tos 0x0, ttl 64, id 34539, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x6e87), seq 31901704, ack 241450086, win 749, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86eb 4000 4006 e9ba c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 3c66  ..$e...P.....d<f
	0x0020:  8010 02ed ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.029849 IP (tos 0x0, ttl 64, id 34540, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x68c8), seq 31901704, ack 241451534, win 772, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86ec 4000 4006 e9b9 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 420e  ..$e...P.....dB.
	0x0020:  8010 0304 ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.029967 IP (tos 0x0, ttl 64, id 34541, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x630a), seq 31901704, ack 241452982, win 794, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86ed 4000 4006 e9b8 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 47b6  ..$e...P.....dG.
	0x0020:  8010 031a ca44 0000 0101 080a 112d 419a  .....D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.030090 IP (tos 0x0, ttl 64, id 34542, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x5d4b), seq 31901704, ack 241454430, win 817, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86ee 4000 4006 e9b7 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 4d5e  ..$e...P.....dM^
	0x0020:  8010 0331 ca44 0000 0101 080a 112d 419a  ...1.D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.030218 IP (tos 0x0, ttl 64, id 34543, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x578d), seq 31901704, ack 241455878, win 839, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86ef 4000 4006 e9b6 c0a8 2468  E..4..@.@.....$h
	0x0010:  c0a8 2465 c6d6 0050 01e6 c808 0e64 5306  ..$e...P.....dS.
	0x0020:  8010 0347 ca44 0000 0101 080a 112d 419a  ...G.D.......-A.
	0x0030:  0006 0c7e                                ...~
18:15:11.030336 IP (tos 0x0, ttl 64, id 34544, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.36.104.50902 > 192.168.36.101.80: Flags [.], cksum 0xca44 (incorrect -> 0x51ce), seq 31901704, ack 241457326, win 862, options [nop,nop,TS val 288178586 ecr 396414], length 0
	0x0000:  4500 0034 86f0 4000 4006 e9b5 c0a8 2468  E..4..@.@.....$h`

**Comment by Phyks** [comment]
A few things on this:

1. There was [a bug](https://github.com/ampache/ampache/pull/1276) in the underlying library we use for localplay in Kodi. Could you try updating your instance (or installing a new one besides) using the [`develop` branch](https://github.com/ampache/ampache/tree/develop) and see if the issue is still around? Not that you should run [`composer install --prefer-source --no-interaction`](https://github.com/ampache/ampache/wiki/Upgrade) to ensure every 3rd party lib is up to date.

2. Do you have an estimated date / version (for both Ampache and Kodi) when it was actually working? And when it stopped working (I guess it was around late november 2015, date of your first message on this issue)? This is to narrow done the possible changes affecting it.

3. Thanks for the `tcpdump` snippet. The only query I see is the `GET /jsonrpc` query, which should be the call from Ampache to Kodi JSON API. I do not see any subsequent HEAD call, which was mentionned by @Afterster and seemed to be the root of the issue.

I will try to setup a Kodi instance on my own to be more helpful in debugging this :)

**Comment by nakinigit** [comment]
1. I'm on 3.8.3-develop, composer updated. Tried creating new instance, no change.
2. It's been a while, I'm a little foggy on when. But it seems to me that the problem started when I transitioned from xbmc to kodi

**Comment by mexthecat** [comment]
I have changed this in xbmc.controller.php on line 316:

            if ($status['state'] == 'stop') {
to
            if ($status['state'] == 'stop' || $status['state'] == 'play') {

kodi returns 'play' state even if I have stopped the player.

Maybe it helps.

**Comment by Phyks** [comment]
Is it working for you after this fix?

**Comment by mexthecat** [comment]
Sorry for the late reply - Yes ... I've changed this and now everything is working fine.

**Comment by Afterster** [comment]
Thanks @mextthecat.
Then I am correct to understand that this is a bug at Kofi API side? Either the Kodi logic changed somehow and Ampache must be updated, or this bug should be fixed at Kodi.

**Comment by manishjhawar** [comment]
This fix hasn't yet been applied to the master tree. Is a PR required?

**Comment by wagnered** [comment]
@manishjhawar,

I would appreciate someone taking it upon themselves to create a PR as I have submitted a change to .travis.yml that needs to be tested.  Also, I am the only one currently working on issues and the Laravel based version of Ampache.

If someone takes it upon themselves to create the PR, please clone the latest commit (a587069) to get all the latest changes.

Also, It would also be appreciated if someone could edit the wiki to include setting up kodi for localplay with Amapache.

Thanks,

Ernie D

**Comment by mitchray** [comment]
Quite some time has passed on this, closing for now unless someone can confirm this is still relevant

**Comment by graduatio** [comment]
Local play with Kodi still fails with the log messages mentioned in the original post. After adjusting xbmc.controller.php as recommended by @mexthecat the error message in the log disappears but local play still does not work for me. The playlist in Kodi only shows "index.php" instead of the song titles and the playback does not start.

**Comment by lusum** [comment]
Ok, after a long session of testing here the results:

a)The only documentation about url in playlist is [here](https://forum.kodi.tv/showthread.php?tid=155888) , but not so much useful

b)Testing with an url from archive.org i can see the filename in the list, the problem with index.php is probabily the lack of sanitation of the url we send to kodi ( no expert, so i tend to skip )

c)Once started manually the playlist, the plugin works as expected ( skip, play, pause, volume .. )

So.. the problem lies in the stream_url sanitation ( function add_url in AmpacheXbmc.php )

**Comment by lusum** [comment]
> Local play with Kodi still fails with the log messages mentioned in the original post. After adjusting xbmc.controller.php as recommended by @mexthecat the error message in the log disappears but local play still does not work for me. The playlist in Kodi only shows "index.php" instead of the song titles and the playback does not start.

Playback is fixed in the pull request, about index.php i think is an url rewrite issue.

**Comment by lusum** [comment]
Except for url rewrite the bug is solved

**Comment by graduatio** [comment]
@lusum Thanks for solving this issue and for your hint regarding "index.php". The "index.php" in the playlist seemed to be caused in my case by using kodi with ssl enabled. Local play with kodi now works for me with ampache 5.4.0 when using the web interface. When using the play:Sub client on ios in jukebox mode ampache still only loads the playlist to kodi but does not start the playback. I don't know if it is a problem with the local play module or with the subsonic jukebox API.

**Comment by lusum** [comment]
I think that the jukebox mode problem is a problem related to #2934

**Comment by lusum** [comment]
The jukebox problem is not related to ampache localplay. I have tested with ultrasonic and jukebox mode. It is a problem of subsonic api. One example. Adding an url to ampache correctly takes the form http://serveraddr/play/.... , instead subsonic jukebox mode generates an url like: http://localhost/play. This bug could be closed cause is related to another bug.

**Comment by lusum** [comment]
Playback fixed with https://github.com/ampache/ampache/pull/3781

**Comment by lusum** [comment]
fixed with https://github.com/ampache/ampache/pull/3794 , issue to close
