### ISSUE TITLE
Subsonic backend doesn't appear to send art under nginx

### ISSUE THREAD

**Issue by Nukien** [ampache/ampache#1051]
I have Ampache 3.8.2-develop installed in /var/www/ampache being served up via nginx.  Everything seems to work fine, except for artwork via subsonic.  The website at http://installerbox.local/ampache seems to be fine, and can play locally via the browser.

Using Clementine as a client, it can log into http://installerbox.local/ampache and retrieve the music, and play it just fine.  But no artwork.  This is the nginx access log log when doing a *Refresh catalogue* from Clementine.  
```
192.168.2.101 - - [14/Dec/2015:12:36:14 -0500] "GET /ampache/rest/getAlbumList2.view?v=1.8.0&c=Clementine&u=clementine&p=password&type=alphabeticalByName&size=500&offset=0 HTTP/1.1" 200 355 "-" "Mozilla/5.0"
192.168.2.101 - - [14/Dec/2015:12:36:14 -0500] "GET /ampache/rest/getAlbumList2.view?v=1.8.0&c=Clementine&u=clementine&p=password&type=alphabeticalByName&size=500&offset=500 HTTP/1.1" 200 161 "-" "Mozilla/5.0"
192.168.2.101 - - [14/Dec/2015:12:36:14 -0500] "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001966 HTTP/1.1" 200 842 "-" "Mozilla/5.0"
192.168.2.101 - - [14/Dec/2015:12:36:14 -0500] "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001965 HTTP/1.1" 200 993 "-" "Mozilla/5.0"
192.168.2.101 - - [14/Dec/2015:12:36:14 -0500] "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001964 HTTP/1.1" 200 1245 "-" "Mozilla/5.0"
```
I've turned on logging of rewrite rules to see what's going on.
```
2015/12/14 12:29:34 [notice] 10485#0: *32 "^/ampache/rest/(.*).view$" matches "/ampache/rest/getAlbumList2.view", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/getAlbumList2.view?v=1.8.0&c=Clementine&u=clementine&p=password&type=alphabeticalByName&size=500&offset=0 HTTP/1.1", host: "installerbox.local"
2015/12/14 12:29:34 [notice] 10485#0: *32 rewritten data: "/ampache/rest/index.php", args: "action=getAlbumList2&v=1.8.0&c=Clementine&u=clementine&p=password&type=alphabeticalByName&size=500&offset=0", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/getAlbumList2.view?v=1.8.0&c=Clementine&u=clementine&p=password&type=alphabeticalByName&size=500&offset=0 HTTP/1.1", host: "installerbox.local"
2015/12/14 12:29:34 [notice] 10485#0: *32 "^/ampache/rest/(.*).view$" matches "/ampache/rest/getAlbumList2.view", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/getAlbumList2.view?v=1.8.0&c=Clementine&u=clementine&p=password&type=alphabeticalByName&size=500&offset=500 HTTP/1.1", host: "installerbox.local"
2015/12/14 12:29:34 [notice] 10485#0: *32 rewritten data: "/ampache/rest/index.php", args: "action=getAlbumList2&v=1.8.0&c=Clementine&u=clementine&p=password&type=alphabeticalByName&size=500&offset=500", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/getAlbumList2.view?v=1.8.0&c=Clementine&u=clementine&p=password&type=alphabeticalByName&size=500&offset=500 HTTP/1.1", host: "installerbox.local"
2015/12/14 12:29:34 [notice] 10485#0: *32 "^/ampache/rest/(.*).view$" matches "/ampache/rest/getAlbum.view", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001964 HTTP/1.1", host: "installerbox.local"
2015/12/14 12:29:34 [notice] 10485#0: *32 rewritten data: "/ampache/rest/index.php", args: "action=getAlbum&v=1.8.0&c=Clementine&u=clementine&p=password&id=200001964", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001964 HTTP/1.1", host: "installerbox.local"
2015/12/14 12:29:34 [notice] 10485#0: *36 "^/ampache/rest/(.*).view$" matches "/ampache/rest/getAlbum.view", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001965 HTTP/1.1", host: "installerbox.local"
2015/12/14 12:29:34 [notice] 10485#0: *36 rewritten data: "/ampache/rest/index.php", args: "action=getAlbum&v=1.8.0&c=Clementine&u=clementine&p=password&id=200001965", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001965 HTTP/1.1", host: "installerbox.local"
2015/12/14 12:29:34 [notice] 10485#0: *38 "^/ampache/rest/(.*).view$" matches "/ampache/rest/getAlbum.view", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001966 HTTP/1.1", host: "installerbox.local"
2015/12/14 12:29:34 [notice] 10485#0: *38 rewritten data: "/ampache/rest/index.php", args: "action=getAlbum&v=1.8.0&c=Clementine&u=clementine&p=password&id=200001966", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001966 HTTP/1.1", host: "installerbox.local"
```
Everything seems to be OK.  But it doesn't seem to hitting the beautiful URL rewriting bits in the nginx config.  Note, I've added `&thumb=$4&name=art.jpg` as per the */play/.htaccess* file.

```
   # Beautiful URL Rewriting
   rewrite ^/ampache/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/name/(.*)$ /ampache/play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&name=$5 last;
   rewrite ^/ampache/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/name/(.*)$ /ampache/play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&name=$7 last;
   location  /ampache/play {
      if (!-e $request_filename) {
         # Original rewrite here - testing addition of &thumb=$4&name=art.jpg per /ampache/play/.htaccess
         # rewrite ^/ampache/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /ampache/image.php?object_type=$2&object_id=$3&auth=$1;
         rewrite ^/ampache/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /ampache/image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg;
         break;
      }

      rewrite ^/([^/]+)/([^/]+)(/.*)?$ /ampache/play/$3?$1=$2;
      rewrite ^/(/[^/]+|[^/]+/|/?)$ /ampache/play/index.php last;
      break;
   }
```

I've also tested with the Chrome app **Polysonic** with the same results.  Everything seems to work fine, except no artwork.  There don't seem to be any errors logged - it's as if Clementine/Polysonic are just not requesting `/ampache/play/art/.....`

Any ideas ?

**Comment by Nukien** [comment]
Quick update ...  Just tested with Android Subsonic app, and that seems to work perfectly.  Gets media and artwork.

So perhaps something is up with Clementine and Polysonic ?

**Comment by Afterster** [comment]
It doesn't seems to be related to nginx rewrite rule, the art request should be something like /ampache/rest/getCovertArt?......
In fact after investigation it seems to be an unsupported feature for now. These clients are making the request with a prefix on item identifier: /ampache/rest/getCoverArt.view?u=admin&v=1.11.0&c=PolySonic&f=json&p=enc:74657374&size=550&id=al-200000054
We have to support that, I will fix it soon :)

**Comment by Nukien** [comment]
Ah ha.  So I can scoop my brains back up off the desk where they fell out as I was beating my head against it.

Looking forward :)

**Comment by Afterster** [comment]
I just committed changes to ignore those prefixes.

**Comment by Nukien** [comment]
Just saw this coming, so did a **git pull**
```
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 17 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), done.
From https://github.com/ampache/ampache
   f4d96e6..6c9f55e  develop    -> origin/develop
Updating b90a642..6c9f55e
Fast-forward
 composer.json                                                      |  7 +++----
 composer.lock                                                      |  4 ++--
 lib/class/subsonic_xml_data.class.php                              | 17 ++++++++++++++++-
 modules/catalog/dropbox/{composer.json => composer.module.json}    |  0
 modules/catalog/remote/{composer.json => composer.module.json}     |  0
 modules/catalog/soundcloud/{composer.json => composer.module.json} |  0
 modules/localplay/xbmc/{composer.json => composer.module.json}     |  0
 modules/plugins/Tmdb/{composer.json => composer.module.json}       |  0
 modules/plugins/Tvdb/{composer.json => composer.module.json}       |  0
 9 files changed, 21 insertions(+), 7 deletions(-)
 rename modules/catalog/dropbox/{composer.json => composer.module.json} (100%)
 rename modules/catalog/remote/{composer.json => composer.module.json} (100%)
 rename modules/catalog/soundcloud/{composer.json => composer.module.json} (100%)
 rename modules/localplay/xbmc/{composer.json => composer.module.json} (100%)
 rename modules/plugins/Tmdb/{composer.json => composer.module.json} (100%)
 rename modules/plugins/Tvdb/{composer.json => composer.module.json} (100%)
```

Hrm - just re-read your post.  You're ignoring the prefixes, not actually processing them and returning the art.  Which makes sense, since clementine/polysonic still didn't get art ...

**Comment by Afterster** [comment]
Ok I was able to reproduce your issue and to fix it with 799165a119ca32e478c87e74357608c5577a11eb :smile:

**Comment by Nukien** [comment]
Polysonic and Jamstash (chrome) are both working nicely now.  Clementine still doesn't get artwork.  Here's the access log from nginx

```
192.168.2.101 - - [17/Dec/2015:17:08:30 -0500] "GET /ampache/rest/getAlbumList2.view?v=1.8.0&c=Clementine&u=clementine&p=password&type=alphabeticalByName&size=500&offset=0 HTTP/1.1" 200 481 "-" "Mozilla/5.0"
192.168.2.101 - - [17/Dec/2015:17:08:30 -0500] "GET /ampache/rest/getAlbumList2.view?v=1.8.0&c=Clementine&u=clementine&p=password&type=alphabeticalByName&size=500&offset=500 HTTP/1.1" 200 161 "-" "Mozilla/5.0"
192.168.2.101 - - [17/Dec/2015:17:08:30 -0500] "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001967 HTTP/1.1" 200 672 "-" "Mozilla/5.0"
192.168.2.101 - - [17/Dec/2015:17:08:30 -0500] "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001968 HTTP/1.1" 200 811 "-" "Mozilla/5.0"
192.168.2.101 - - [17/Dec/2015:17:08:30 -0500] "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001965 HTTP/1.1" 200 998 "-" "Mozilla/5.0"
192.168.2.101 - - [17/Dec/2015:17:08:30 -0500] "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001964 HTTP/1.1" 200 1250 "-" "Mozilla/5.0"
192.168.2.101 - - [17/Dec/2015:17:08:30 -0500] "GET /ampache/rest/getAlbum.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=200001966 HTTP/1.1" 200 847 "-" "Mozilla/5.0"
```
This is when I do a **Refresh catalogue** from Clementine.  Are there other logs or more details that you need ?

**Comment by Afterster** [comment]
Ok good to know.
I don't think Clementine support album art, demo.subsonic.org is getting the same result than Ampache.

**Comment by Nukien** [comment]
Hrm - it does support album art for Library items.  Subsonic is under "Internet" as a remote source.  Perhaps it doesn't do album art for Internet sources ?

Here's what Voodoo Child looks like as a Library item (local via NFS)
![Clementine local Library](http://s23.postimg.org/6lcstapjf/Workspace_1_001.png)

And here it is via Subsonic
![Clementine via Subsonic](http://s22.postimg.org/a77g4bn9d/Workspace_1_002.png)

**Comment by Afterster** [comment]
Yes, I means Clementine doesn't support album art through Subsonic sources. In fact there is an issue opened about that on Clementine issue tracker. See https://github.com/clementine-player/Clementine/issues/4370

**Comment by Nukien** [comment]
Ah, got it.  Looks like we're good here then :)
