### ISSUE TITLE
Subsonic backend broken with nginx and SSL

### ISSUE THREAD

**Issue by Nukien** [ampache/ampache#1062]
I must have borked something somewhere - this was working under http a few days ago.  I've done at least a dozen installs as I build up my auto-installer script, tweaking here, there. This is set up on Ubuntu 14.04.3 with nginx 1.8.0 all via SSL.  The music is all under `/Media/Music/Tagged` and there's a single catalog pointing to `/Media/Music/Tagged/Voodoo Child` which has 2 albums under it.

So, everything works fine in the browser - the whole setup, playing tracks, everything.  Subsonic clients are not working right now, tested with Clementine on Linux and Subsonic on Android.  Here are the various relevant bits ...

nginx config

```
location /ampache {
   auth_basic off;
   # Rewrite rule for Subsonic backend
   if ( !-d $request_filename ) {                                                                         
      rewrite ^/ampache/rest/(.*).view$ /ampache/rest/index.php?action=$1 last;                      
      rewrite ^/ampache/rest/fake/(.+)$ /ampache/play/$1 last;                                       
   }                                                                                                      
   # Beautiful URL Rewriting
   rewrite ^/ampache/play/ssid/(w+)/type/(w+)/oid/([0-9]+)/uid/([0-9]+)/name/(.*)$ /ampache/play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&name=$5 last;
   rewrite ^/ampache/play/ssid/(w+)/type/(w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/name/(.*)$ /ampache/play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&name=$7 last;

   location  /ampache/play {
      if (!-e $request_filename) {
         rewrite ^/ampache/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*).([a-z]+)$ /ampache/image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg;
         break;   
      }
      rewrite ^/([^/]+)/([^/]+)(/.*)?$ /ampache/play/$3?$1=$2;
      rewrite ^/(/[^/]+|[^/]+/|/?)$ /ampache/play/index.php last;
      break;
   }
}
```

Clementine and Subsonic-android are logged in as **clementine**/_password_ and get a good list of albums/artists/tracks etc.  It's just playing the track that fails.

ampache.cfg.php

```
http_host = "installerbox.local"
web_path = "/ampache" 
local_web_path = "https://installerbox.local/ampache"
```

nginx access log - just clementine test

```
192.168.2.146 - - [19/Dec/2015:18:16:44 -0500] "GET /ampache/play/ssid/e267a725406ec8b39ec164add8a66882/type/song/oid/14/uid/2/client/Clementine/noscrobble/1/player/api/name/Voodoo%20Child%20-%20Minors.mp3 HTTP/1.1" 404 168 "-" "Clementine 1.2.3"
192.168.2.101 - - [19/Dec/2015:18:16:44 -0500] "GET /ampache/rest/stream.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=300000014 HTTP/1.1" 404 168 "-" "Clementine 1.2.3"
```

nginx error log (with rewrite logging turned on) clementine and android tests

```
2015/12/19 18:16:44 [notice] 14468#0: *4 "^/ampache/rest/(.*).view$" matches "/ampache/rest/stream.view", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/stream.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=300000014 HTTP/1.1", host: "installerbox.local"
2015/12/19 18:16:44 [notice] 14468#0: *4 rewritten data: "/ampache/rest/index.php", args: "action=stream&v=1.8.0&c=Clementine&u=clementine&p=password&id=300000014", client: 192.168.2.101, server: installerbox.local, request: "GET /ampache/rest/stream.view?v=1.8.0&c=Clementine&u=clementine&p=password&id=300000014 HTTP/1.1", host: "installerbox.local"
2015/12/19 18:16:44 [notice] 14468#0: *6 "^/ampache/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*).([a-z]+)$" does not match "/ampache/play/ssid/e267a725406ec8b39ec164add8a66882/type/song/oid/14/uid/2/client/Clementine/noscrobble/1/player/api/name/Voodoo Child - Minors.mp3", client: 192.168.2.146, server: installerbox.local, request: "GET /ampache/play/ssid/e267a725406ec8b39ec164add8a66882/type/song/oid/14/uid/2/client/Clementine/noscrobble/1/player/api/name/Voodoo%20Child%20-%20Minors.mp3 HTTP/1.1", host: "installerbox.local"
2015/12/19 18:16:44 [error] 14468#0: *6 open() "/var/www/ampache/play/ssid/e267a725406ec8b39ec164add8a66882/type/song/oid/14/uid/2/client/Clementine/noscrobble/1/player/api/name/Voodoo Child - Minors.mp3" failed (2: No such file or directory), client: 192.168.2.146, server: installerbox.local, request: "GET /ampache/play/ssid/e267a725406ec8b39ec164add8a66882/type/song/oid/14/uid/2/client/Clementine/noscrobble/1/player/api/name/Voodoo%20Child%20-%20Minors.mp3 HTTP/1.1", host: "installerbox.local"

2015/12/19 18:48:36 [error] 14468#0: *507 open() "/var/www/ampache/play/ssid/59d3611d2b22b8120ded96075baac34f/type/song/oid/13/uid/1/client/android/noscrobble/1/player/api/name/Voodoo Child - Take It Home.mp3" failed (2: No such file or directory), client: 192.168.2.146, server: installerbox.local, request: "GET /ampache/play/ssid/59d3611d2b22b8120ded96075baac34f/type/song/oid/13/uid/1/client/android/noscrobble/1/player/api/name/Voodoo%20Child%20-%20Take%20It%20Home.mp3 HTTP/1.1", host: "installerbox.local"
```

For example, the track to be played is `/Media/Music/Tagged/Voodoo Child/Voodoo Child - Minors.mp3` (or `Take it Home.mp3` from android)
Yet it looks like it's trying to open the mp3 using the entire URL as the filename rather than mapping it to correct location.
`/var/www/ampache/play/ssid/e267a725406ec8b39ec164add8a66882/type/song/oid/14/uid/2/client/Clementine/noscrobble/1/player/api/name/Voodoo Child - Minors.mp3`

Any ideas ?  I don't know if the issue is in the nginx rewriting or in ampache not mapping to the correct on-disk location.

**Comment by psjbeisler** [comment]
ive had this issue for a while with the same setup nginx+ssl but it only happens if I turn on URL rewriting. I will get this error trying to stream to a device, the web player will work, but i will be missing album art...

**Comment by Afterster** [comment]
I don't use nginx but I believe provided rewrite rules is incomplete
Try to add a line like
`rewrite ^/ampache/play/ssid/(w+)/type/(w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/api/(.*)/name/(.*)$ /ampache/play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&api=$7&name=$8 last;`
Having an nginx user updating Ampache wiki would be better, if anyone is hearing :)

**Comment by pyongyang666** [comment]
Subsonic api on my nginx setup seems to be working after a great deal of fiddling. Clementine is playing music from it. I've updated the wiki accordingly.

**Comment by Afterster** [comment]
thanks @pyongyang666 but is your addition not a duplicate with existing
```
# Rewrite rule for Subsonic backend
   if ( !-d $request_filename ) {
      rewrite ^/rest/(.*).view$ /rest/index.php?action=$1 last;
      rewrite ^/rest/fake/(.+)$ /play/$1 last;
   }
```

Looks a duplicate to me but I'm not a nginx user as said.

**Comment by pyongyang666** [comment]
Essentially. I'm still fine tuning the solution and I'm not exactly a fan of deleting other peoples work without their permission.

**Comment by kelvinhammond** [comment]
I had some of the same issues. The rewrite rules on the wiki are a bit outdated.
These worked for me with [DSub](https://github.com/daneren2005/Subsonic). There was also a typo in the regex on the wiki (`(w)` instead of `(\w)`). Those issues are fixed in my rewrite rules below.

```
   rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&name=$5 last;
   rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&name=$7 last;
   rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/api/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&api=$7&name=$8 last;
   rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/clienT/(.*)/noscrobble/([0-1])/transcode_to/(w+)/bitrate/([0-9]+)/api/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&transcode_to=$7&bitrate=$8&api=$9&name=$10 last;
   rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/bitrate/([0-9]+)/player/api/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&bitrate=$7&name=$8 last;
```

After adding the last rewrite url DSub was able to play music. I'm not transcoding my FLAC files but DSub still sends a bitrate for whatever reason (default: `320`).

**Comment by Afterster** [comment]
Thank you for updating the wiki, having a good configuration for nginx is important!
Could some other users confirm the provided rewrite rules fix it? @pyongyang666 @psjbeisler @Nukien?

**Comment by Halfwalker** [comment]
Shouldn't the transcode rewrite use \w+ as well ?

/transcode_to/(**w+**)/bitrate/

**Comment by Halfwalker** [comment]
I'm fiddling with it now - no luck yet with Clementine :(  For example, this is the GET request in the access log :

> GET /ampache/play/ssid/53dd203870c8ac546a2fbb83f2f58263/type/song/oid/14/uid/1/client/Clementine/noscrobble/1/player/api/name/Voodoo%20Child%20-%20Minors.mp3 HTTP/1.1" 404 168 "-" "Clementine 1.2.3"

And the error log notification

> [error] 20570#0: *9 open() "/var/www/ampache/play/ssid/53dd203870c8ac546a2fbb83f2f58263/type/song/oid/14/uid/1/client/Clementine/noscrobble/1/player/api/name/Voodoo Child - Minors.mp3" failed (2: No such file or directory),

This is the rewrite rule that should match that GET request - the numbers are above the captures that go into $1 $2 etc.  Unfortunately, it doesn't, or at least I still get those errors and no music playing.

```
#                             1          2          3            4             5                 6                     7
rewrite ^/ampache/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/player/api/name/(.*)$  /ampache/play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&name=$7 last;
```

**Comment by Frank12B** [comment]
Hi,
I updated the wiki with my nginx.conf which is working with nginx 1.6.2/openmediavault3.X/debian 8 and ssl enabled. Maybe give it a try.

**Comment by Afterster** [comment]
Ok, thanks @Frank12B.
@Halfwalker could you give a try with these changes?

**Comment by Halfwalker** [comment]
No luck :(

This is from nginx error log
> 016/02/27 09:54:28 [error] 27225#0: *75 open() "/var/www/ampache/play/ssid/2a075ba196e5d09051714c71cafc2232/type/song/oid/14/uid/1/client/Clementine/noscrobble/1/player/api/name/Voodoo Child - Minors.mp3" failed (2: No such file or directory), client: 127.0.0.1, server: ubutest.local, request: "GET /ampache/play/ssid/2a075ba196e5d09051714c71cafc2232/type/song/oid/14/uid/1/client/Clementine/noscrobble/1/player/api/name/Voodoo%20Child%20-%20Minors.mp3 HTTP/1.1", host: "Ubutest.local"

And here is the access log :
> 127.0.0.1 - - [27/Feb/2016:09:54:28 -0500] "GET /ampache/play/ssid/2a075ba196e5d09051714c71cafc2232/type/song/oid/14/uid/1/client/Clementine/noscrobble/1/player/api/name/Voodoo%20Child%20-%20Minors.mp3 HTTP/1.1" 404 168 "-" "Clementine 1.2.3"

**Comment by Afterster** [comment]
Related to your environment here, we cannot fix it for you.
You should try with basic rewritre rules to see if it works for test and then try to use Ampache ones. Good luck.

**Comment by Halfwalker** [comment]
Yeah, this is really strange.

**Comment by Phyks** [comment]
Any news on this or should it be closed?

**Comment by StephanX** [comment]
I may have found a solution.

I couldn't get dsub to work with my setup, after following the wiki.  Adding: 

    # only optional for ssl encryption enabled: Path to certificate/key
        ssl on;
        error_page 497 =200 $request_uri;

Turned out to be the culprit.  I figured it out by upping error logging to info:

         error_log       /var/log/ampache/error.log info ;

And saw "client sent plain HTTP request to HTTPS port while reading client request headers," spamming the error logs.

**Comment by AshotN** [comment]
This is old enough to probably no longer be relevant. If anyone needs furthur support please create a new ticket.
