### ISSUE TITLE
Subsonic API doesn't work

### ISSUE THREAD

**Issue by lavacano201014** [ampache/ampache#1916]
# Environment

 * Ampache version: 3.8.2
 * Web server + version: [Docker](https://hub.docker.com/r/ampache/ampache/)
 * Server operating system: Ubuntu 18.04
 * Client operating system: Android

 * Client type:
   - SubSonic: any

# Settings and Logs

[ampache.zip](https://github.com/ampache/ampache/files/3280017/ampache.zip)

# Description
Subsonic clients cannot download songs. I've tried both the official Subsonic client and DSub.
 - URL rewriting and Subsonic backend are enabled in Ampache settings.
 - .htaccess files are correct
 - `avconv` seems to work in the Docker container.
 - Web player works just fine.
 - `/rest/ping.view` returns a Subsonic response.

**Comment by lachlan-00** [comment]
is this using the official docker?

**Comment by alejandroliu** [comment]
I have tested a docker ampache with two subsonic iPhone clients: substreamer and iSub.  iSub works fine, substreamer (ironically enough) is not able to stream songs, but if I make the songs offline, then playback works fine.

I am not using the "official" docker, as that is quite out of date.  I am using the image "zerodogg/ampache-apache" paired with an external database on a different container.

**Comment by lachlan-00** [comment]
You'll have to make a report to the gitlab repo or make a report on the official repo (https://github.com/ampache/ampache-docker) and tag @zerodogg in it.

I've asked him if he'd like to maintain the official repo but if he doesn't get back to me i'll update the official image after Ampache 4.0.0 is released.

Once 4.0.0 is out and if ampache-docker doesn't have a maintainer. i'll be update the docker repo myself. It's just not a priority for me until the next release is out.

**Comment by lavacano201014** [comment]
I just ended up throwing Docker out entirely and configuring Apache2 and MySQL on the box directly, and now it works.

That's what I get for being lazy and trying to use pre-configured stuff, I guess :V

**Comment by lachlan-00** [comment]
Docker is great but the reason i don't use it is for the same reasons.

Hopefully we can make it better this year

**Comment by bmcgonag** [comment]
Soooooo. should this have been resolved?  I'm using the docker version and neither iSub, nor Substreamer will stream the music.  iSub gives an error, but Substreamer just sits there...never playing.  

Both load the song list and cover art, but wont' stream.  I'm using the official ampache/ampache docker.

**Comment by bmcgonag** [comment]
Ok, starting to work. Had to set some different settings in the web interface.  I can stream individual songs, but not playlists yet.

**Comment by bmcgonag** [comment]
Ok, nevermind, looks like Ihave some .opus files left that just won't stream.  I thought I had converted them all.

**Comment by miltonardila** [comment]
> Ok, starting to work. Had to set some different settings in the web interface. I can stream individual songs, but not playlists yet.

Hi, please what settings did you move in the web interface, I have the same problem with Ampache Docker, thanks.

**Comment by miltonardila** [comment]
Hello, please some help. I have this project pending, still can't hear anything. Thank you.
