### ISSUE TITLE
Problem with ACL stream and access denied with develop 4.0.0 

### ISSUE THREAD

**Issue by rodrigoesborges** [ampache/ampache#2027]
First of all I would like to thank the team/community for this great piece of free software. I have been using it for two years now, and very happy with it.

Since upgrading to version 4.0.0 (develop branch) I started having a similar issue, which makes my installation unusable if I set ACL to true (access_control = true) in config ; of course, with that turned off I cannot use my android client anymore (ultrasonic) .

I tried to find solutions or info on it at ampache's google group and here, without success.

I get this in my log, whenever I try to play anything with ACL on:

> (play/index) -> Streaming Access Denied:  does not have stream level access

as soon as I enable ACL, I cannot even login from the web interface, and receive this message:

"You have been redirected to this page because you do not have access to this function.

If you believe this is an error please contact an Ampache administrator.

This event has been logged."

With this being added to the log:

> [ampache] (login.class) -> UI::access_denied: is not in the Interface Access list 

I had everything working before, with ACL open for everything. Currently I have:

> 

DEFAULTv4 | 0.0.0.0 | 255.255.255.255 | All | All | Web Interface |  
-- | -- | -- | -- | -- | -- | --
DEFAULTv6 | :: | ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff | All | All | Web Interface |  
DEFAULTv4 | 0.0.0.0 | 255.255.255.255 | All | All | API/RPC |  
DEFAULTv4 | 0.0.0.0 | 255.255.255.255 | All | All | Stream Access |  
DEFAULTv6 | :: | ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff | All | All | API/RPC |  
DEFAULTv6 | :: | ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff | All | All | Stream Access |  

I can't figure out what happened, and my older nginx files were working well up to version 3.9.x (I think I was on version 3.9.3 before the upgrade, not sure about that)

My setup has php 7.3.7 and nginx 1.17.2

Tried using nginx conf file adapted from [this comment](https://github.com/ampache/ampache/issues/1757#issuecomment-497569878) as suggested by @lachlan-00 in [another issue](https://github.com/ampache/ampache/issues/2025#issuecomment-524686647) , to no avail.

**Comment by lachlan-00** [comment]
thanks, i'll have a dig into the ACL structure and get back to you

**Comment by rodrigoesborges** [comment]
Thanks!

I can try to help more, if given some directions/clues how to try to help debugging.

**Comment by lachlan-00** [comment]
it should be okay, i'll let you know.

I'm just finishing up some api work and this is next. I'll be looking at releasing 4 after i check this issue out properly.

**Comment by lachlan-00** [comment]
I think this might be fixed in develop now. I had split api and stream sessions apart but there were other issues causing me to put them back.

**Comment by rodrigoesborges** [comment]
I checked out the latest changes and tried again. No luck. Still get the same errors.

**Comment by lachlan-00** [comment]
Streaming error or interface?

I have had the ACL enabled for years so we'll need to dig into this a bit more

**Comment by rodrigoesborges** [comment]
Cannot even log in, I receive 403 error on log and this message on the landing page

> "You have been redirected to this page because you do not have access to this function. 
> If you believe this is an error please contact an Ampache administrator.
> This event has been logged."

**Comment by lachlan-00** [comment]
Here is my ACL which doesn't seem any different from yours.
```
Name 	Start Address 	End Address 	Level 	User 	Type 	Action
DEFAULTv4 	0.0.0.0 	255.255.255.255 	All 	All 	Web Interface 	Edit Delete
DEFAULTv4 	0.0.0.0 	255.255.255.255 	All 	All 	Stream Access 	Edit Delete
DEFAULTv6 	:: 	ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff 	All 	All 	Web Interface 	Edit Delete
DEFAULTv6 	:: 	ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff 	All 	All 	Stream Access 	Edit Delete
rpc 	0.0.0.0 	255.255.255.255 	All 	All 	API/RPC
```

It seems like its nginx specific so I might have to reinstall that

**Comment by rodrigoesborges** [comment]
Could it be so? But It wouldn't be an issue with url rewriting , would it ?

**Comment by lachlan-00** [comment]
a lot of things use rewrite rules like images and play urls. it could be something simple as that.

maybe upload your nginx config here and i'll use it on my database to try out.

**Comment by rodrigoesborges** [comment]
> maybe upload your nginx config here and i'll use it on my database to try out.
Here it goes:
`
server {
	listen 80;
	return 301 https://$host:$request_uri;
    	server_name HOSTNAME;
}

server {
    listen 443 ssl; 

    server_name HOSTNAME;
    charset utf-8;

         error_log       /var/log/HOSTNAME/error.log; 
        access_log      /var/log/HOSTNAME/access.log;
       rewrite_log     on;

 ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:EDH+aRSA:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!SEED:!DSS:!CAMELLIA;
    ssl_prefer_server_ciphers on;
    add_header Strict-Transport-Security max-age=15768000;

    # Use secure headers to avoid XSS and many other things
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;
   add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "no-referrer";
    add_header Content-Security-Policy "script-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-src 'self'; object-src 'self'";
	ssl_certificate /SSLCERTLOCATION;
	ssl_certificate_key /SSLKEYLOCATION;

    # Avoid information leak
    server_tokens off;
    fastcgi_hide_header X-Powered-By;

    root /srv/ampache;
    index index.php;

    # Somebody said this helps, in my setup it doesn't prevent temporary saving in files
    proxy_max_temp_file_size 0;

    # Rewrite rule for Subsonic backend
    if ( !-d $request_filename ) {
        rewrite ^/rest/(.*).view$ /rest/index.php?action=$1 last;
        rewrite ^/rest/fake/(.+)$ /play/$1 last;
    }

    # Rewrite rule for Channels
    if (!-d $request_filename){
      rewrite ^/channel/([0-9]+)/(.*)$ /channel/index.php?channel=$1&target=$2 last;
    }

    # Beautiful URL Rewriting
        rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&name=$5 last;
        rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&name=$7 last;
        rewrite ^/play/ssid/(.*)/type/(.*)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&player=$7&name=$8 last;
        rewrite ^/play/ssid/(.*)/type/(.*)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/transcode_to/(w+)/bitrate/([0-9]+)/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&transcode_to=$7&bitrate=$8&player=$9&name=$10 last;
    
    # the following line was needed for me to get downloads of single songs to work
        rewrite ^/play/ssid/(.*)/type/(.*)/oid/([0-9]+)/uid/([0-9]+)/action/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4action=$5&name=$6 last;
        location /play {
                if (!-e $request_filename) {
                rewrite ^/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /image.php?object_type=$2&object_id=$3&auth=$1 last;
                }

        rewrite ^/([^/]+)/([^/]+)(/.*)?$ /play/$3?$1=$2;
        rewrite ^/(/[^/]+|[^/]+/|/?)$ /play/index.php last;
        break;
        }

   location /rest {
      limit_except GET POST {
         deny all;
      }
   }

   location ^~ /bin/ {
      deny all;
      return 403;
   }

   location ^~ /config/ {
      deny all;
      return 403;
   }

   location / {
      limit_except GET POST HEAD{
         deny all;
      }
   }

   location ~ ^/.*.php {
        fastcgi_index index.php;

    # sets the timeout for requests in [s] , 60s are normally enough
        fastcgi_read_timeout 60s;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

    # Mitigate HTTPOXY https://httpoxy.org/
        fastcgi_param HTTP_PROXY "";

    # has to be set to on if encryption (https) is used:
#        fastcgi_param HTTPS on;

        fastcgi_split_path_info ^(.+?\.php)(/.*)$;

    # chose as your php-fpm is configured to listen on
        #fastcgi_pass unix:/var/run/php5-fpm.sock;
         fastcgi_pass 127.0.0.1:8100;
   }

   # Rewrite rule for WebSocket
   location /ws {
        rewrite ^/ws/(.*) /$1 break;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:8100/;
   }
}


`

**Comment by lachlan-00** [comment]
I updated your comment. easy trick is just 3 backticks (```)

**Comment by rodrigoesborges** [comment]
Ah great thanks. As for the problem, I removed all beautiful rewrite options  (lines including  proxy_max_temp_file_size 0; and break;}) . and I still got the issue. Could the problem be in blocks *.phpo or /ws in any way?

**Comment by lachlan-00** [comment]
I don't think the websocket part would be affecting it but i'll be testing nginx again this week to try and work this out.

**Comment by lachlan-00** [comment]
I think i've found this. it's not creating a row in the session table.

**Comment by rodrigoesborges** [comment]
I get this errors when I enable debug loggin:
`[ampache] (login.class) -> UI::access_denied: is not in the Interface Access list `

**Comment by rodrigoesborges** [comment]
I can confirm that when I substitute `$_SERVER['REMOTE_ADDR'] `for the above filter_input expression in login.php and access.class.php  , I can operate on the web interface normally, And even login from a ultrasonic , the Access denied message disappears. 

Is there any bad side issues if I leaved like that for now?

Now I am having issues with subsonic_xml_data.class. But I think that should be object of another issue, right?

**Comment by lachlan-00** [comment]
no issue with that but we'll need to work out why it's not giving a valid ip.

probably a separate issue for subsonic yes.

**Comment by lachlan-00** [comment]
i think i have the code for this. it's meant to filter the hex address to a ip which i think is why this isn't working.
can you show me the debug on this code?
```
        // Clean incoming variables
        $user_ip = filter_input(INPUT_SERVER, 'REMOTE_ADDR', FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES);
        $user_ip = inet_pton($user_ip);
        debug_event('access.class', 'unfiltered ' . $_SERVER['REMOTE_ADDR'], 2);
        debug_event('access.class', 'filtered   ' . $user_ip, 2);
```

**Comment by lachlan-00** [comment]
don't worry i tested this. fix incoming.

**Comment by rodrigoesborges** [comment]
> don't worry i tested this. fix incoming.

The change in lib/class/access.class.php with 

`filter_input(INPUT_SERVER, 'REMOTE_ADDR', FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES);`

Does not work for me. Again I had to change it to $_SERVER['REMOTE_ADDR'] in order to have my instance allowing me to login or play content.

**Comment by lachlan-00** [comment]
Must not like localhost. I'll have to check out why

**Comment by lachlan-00** [comment]
looks like this.
https://bugs.php.net/bug.php?id=49184

i'll add a function in core to get server variables to work around that

**Comment by lachlan-00** [comment]
have a go with this code

```
        // Clean incoming variables
        if (filter_has_var(INPUT_SERVER, $variable)) {
            $user_ip = filter_input(INPUT_SERVER, $variable, FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES);
        } elseif (filter_has_var(INPUT_ENV, $variable)) {
            $user_ip = filter_input(INPUT_ENV, $variable, FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES);
        } elseif (isset($_SERVER[$variable])) {
            $user_ip = filter_var($_SERVER[$variable], FILTER_VALIDATE_IP);
        }
```

**Comment by lachlan-00** [comment]
I've also merged this change into develop again

**Comment by rodrigoesborges** [comment]
Great now this seems to be working!

**Comment by lachlan-00** [comment]
the answer didn't twig until stebe's issue with ipv6 but i've tested this pretty extensively now.

**Comment by rodrigoesborges** [comment]
I'm closing it now then!

**Comment by openhs** [comment]
It seems that it is still not fixed yet.  On a hosting with PHP 7.2 and Apache 2.4 it does not work for me.  This code, which is in Ampache 4.1.1, does not return an IP.

```
        // Clean incoming variables
        $user_ip = filter_has_var(INPUT_SERVER, 'HTTP_X_FORWARDED_FOR')
            ? filter_var(Core::get_server('HTTP_X_FORWARDED_FOR'), FILTER_VALIDATE_IP)
            : filter_var(Core::get_server('REMOTE_ADDR'), FILTER_VALIDATE_IP);
```

Also the code from (https://github.com/ampache/ampache/issues/2027#issuecomment-540313263) is not working.

The code from 3.x works (with renamed variable $ip):

`$user_ip = $user_ip ?: $_SERVER['REMOTE_ADDR'];`

**Comment by lachlan-00** [comment]
you need to provide some logs. the code you've posted is the same as just using the last variable.
```
$user_ip = $_SERVER['REMOTE_ADDR'];
```
so to me that sounds like your HTTP_X_FORWARDED_FOR isn't doing the right thing

**Comment by openhs** [comment]
It seems that filter_has_var returns 1 but values are empty.  I have added few debug lines to access.class:

```
        debug_event('####', 'has_var INPUT_SERVER HTTP_X_FORWARDED_FOR ' . filter_has_var(INPUT_SERVER, 'HTTP_X_FORWARDED_FOR'), 3);
        debug_event('####', 'INPUT_SERVER[HTTP_X_FORWARDED_FOR] "' . $INPUT_SERVER['HTTP_X_FORWARDED_FOR'] . '"', 3);
        debug_event('####', 'has_var INPUT_SERVER REMOTE_ADDR ' . filter_has_var(INPUT_SERVER, 'REMOTE_ADDR'), 3);
        debug_event('####', 'INPUT_SERVER[REMOTE_ADDR] "' . $INPUT_SERVER['REMOTE_ADDR'] . '"', 3);
        debug_event('####', '_SERVER[REMOTE_ADDR] ' . $_SERVER['REMOTE_ADDR'], 3);
        // Clean incoming variables
```
Here is what it's logged after showing a login screen:

```
2020-02-21 16:27:35 [ampache] (####) -> has_var INPUT_SERVER HTTP_X_FORWARDED_FOR 1
2020-02-21 16:27:35 [ampache] (####) -> INPUT_SERVER[HTTP_X_FORWARDED_FOR] ""
2020-02-21 16:27:35 [ampache] (####) -> has_var INPUT_SERVER REMOTE_ADDR 1
2020-02-21 16:27:35 [ampache] (####) -> INPUT_SERVER[REMOTE_ADDR] ""
2020-02-21 16:27:35 [ampache] (####) -> _SERVER[REMOTE_ADDR] 205.185.115.175
2020-02-21 16:27:35 [ampache] (log.lib) -> [Runtime Error] inet_pton(): Unrecognized address  in file /nfsmnt/hosting1_1/6/3/63c68986-1e78-4c20-ab9a-7e36a2c24b80/ampache-browser.org/sub/demotest/lib/class/access.class.php(373)
2020-02-21 16:27:35 [ampache] (log.lib) -> [Runtime Error] inet_pton(): Unrecognized address  in file /nfsmnt/hosting1_1/6/3/63c68986-1e78-4c20-ab9a-7e36a2c24b80/ampache-browser.org/sub/demotest/lib/class/access.class.php(373)
2020-02-21 16:27:35 [ampache] (access.class) -> check_network interface: ip not found in ACL
2020-02-21 16:27:35 [ampache] (login.class) -> UI::access_denied:205.185.115.175 is not in the Interface Access list
```

**Comment by lachlan-00** [comment]
so that looks like it's saying the variable exists but is empty?

which would explain why a null ip address isn't a valid address

**Comment by openhs** [comment]
> so that looks like it's saying the variable exists but is empty?

Yes, exactly.  Additional check for empty values should be added I think.

**Comment by lachlan-00** [comment]
okay, i'll probably be able to do that tonight when i get home.
