### ISSUE TITLE
Grant Last.FM plugin kicks me out of Ampache 5.1.0

### ISSUE THREAD

**Issue by bembudo** [ampache/ampache#3081]
### Describe the bug
When Granting access to Last.FM plugin i am kicked out\ logged out of ampache. When I log back in and check if access to Last FM has been granted it has not, nor does Last FM show that i have a application added.

### To reproduce

reproduced by deactivating plugin and reactivating, accessing plugins section while logged into Last.FM 
ampache.cfg.php contains my token id and secret id

attached is a debug 

[ampache.20211104.log](https://github.com/ampache/ampache/files/7476524/ampache.20211104.log)

* Ampache version: 5.1.0
* Server operating system: Ubuntu 18.04
* Client operating system: Ubuntu 18.04
* 
### Client type

* Web
* Ampache

**Comment by bembudo** [comment]
Hoping someone can take a look. I know this was working just fine in Ampache 4.4.3

**Comment by lachlan-00** [comment]
i see. for starters it should be opening a new window

**Comment by bembudo** [comment]
@lachlan-00  it actually does open a new window. I took a very short screen recording enclosed in a zip for your review
[ampache_screen_record.zip](https://github.com/ampache/ampache/files/7592547/ampache_screen_record.zip)
w

**Comment by lachlan-00** [comment]
it signed me out too, i'll see what the difference is

**Comment by lachlan-00** [comment]
there we go
```
(/var/www/music/src/Repository/Model/Plugin.php:221) -> Call to a member function set_preferences() on string
```

**Comment by bembudo** [comment]
@lachlan-00 im not a developer, is this something i can correct myself or should i wait for this to be corrected in a future build?

**Comment by lachlan-00** [comment]
no, there's something not working correctly in the background.
it's not granting access at all because the user session is disappearing and then unable to write the preference

**Comment by lachlan-00** [comment]
This is actually really annoying, it's creating a new session as soon as i leave the page and then when you go back it's blocking you setting the preference so the session is there but the browser has lost it.

might be a security change? i'm going to look at a different way of doing it.

**Comment by lachlan-00** [comment]
i think i know what this is. the callback is coming form last.fm and then the cookie isn't being kept as it didn't come from the same site (cookie set to strict)

will look at workarounds to keep it strict

**Comment by lachlan-00** [comment]
k, confirmed by strict session cookie

**Comment by lachlan-00** [comment]
@bembudo this is fixed now. I've made the session cookie Lax which makes it readable when coming from external sites like last.fm.

**Comment by lachlan-00** [comment]
it will require develop/5.2 when you but it will also need your cookies cleared as the old strict one will remain for it's duration without clearing

**Comment by bembudo** [comment]
thank you @lachlan-00 Great news, ill wait for the next build

**Comment by mitchray** [comment]
5.2.0 is out now 👍 reopen if its still an issue (remember to clear cookies)

**Comment by bembudo** [comment]
No issues works like a charm 😁 thank you

**Comment by dubwoc** [comment]
When I updated it does not seem to work. 

I deleted all cookies, when I go to the plugin page to go through the authenticate I have a text box labeled: "Last.FM Submit Challenge" which leads me to believe I am in some half state. I poked around the database but didn't see anything obvious to reset.

Any help is much appreciated!

**Comment by stebe** [comment]
what I had to do in my case was disable the plugin and then enable it again and the grant icon reappeared.

**Comment by dubwoc** [comment]
Oh yeah, I forgot that you could disable and enable the plugins, thank you that fixed the problem!
