### ISSUE TITLE
Recently played list no longer includes democratic played songs

### ISSUE THREAD

**Issue by barcoboy** [ampache/ampache#3366]
## Description
Recently played list no longer includes democratic played songs

### Describe the bug
The "Recently Played" list of songs that appears on the main page after logging in no longer seems to take democratic played songs into consideration.  I have a democratic playlist that runs 24/7 using ezstream to send to an Icecast server.  If a song is played inside the GUI via the web player, it will appear at the top of the list, but songs that are fetched using the API URL https://website/play/?apikey=secretkey&uid=1&demo_id=1 do not get included in the recently played list.  However, if I access the URL https://website/stats.php?action=recent, the democratic songs do appear, although the titles are not displayed, only the "Album" information.

## Environment
* Ampache version: f900f30233d78cfae2e950d5f9b0aa1ee9dc486e
* Web server + version: Apache 2.4.52 / PHP 7.4.32
* Server operating system: Slackware 64 15.0 / Linux kernel 5.15.63

**Comment by lachlan-00** [comment]
might be an issue with id'ing the user.

Democratic urls should redirect to a play url which must mean that the APIkey auth isn't getting the user correctly for the play url

I've used this method a lot as well for streaming so i'll be able to confirm today

**Comment by lachlan-00** [comment]
i've had a look and the UID was needed but i've taken that out with 753b3a466

I couldn't see any reason that the stream was stopped using `https://music/play/index.php?apikey=123456&demo_id=1` with or without the uid.

logs okay and then goes in the list

**Comment by lachlan-00** [comment]
i've just fixed those issues this morning so that should be better now

**Comment by barcoboy** [comment]
Trying now with bc7313fb000c59e0d26cdce8c9997cf67db5c484, and getting "403 Session expired", with or without uid parameter.

**Comment by barcoboy** [comment]
Okay that seemed to have got the democratic playlist working again.  But no change with my problem.  I've tried deleting old entries from the recently played list, and then tried clicking "Clear Stats" from the "Show Catalogs" page, which did clear out all entries from the list, but democratic plays still don't get added.  Like before, I can see them appearing on the "Information", "Recent" page, but the homepage says "No recently played items found."

**Comment by lachlan-00** [comment]
i don't have any not showing up for me. do you get any log info about the stream?

on the webserver logs as well it should go from the demo_id url and then redirect to the file play url.
```
192.168.1.9 - - [07/Oct/2022:13:43:57 +1000] "GET /play/index.php?apikey=123456&demo_id=1 HTTP/2.0" 302 314 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.34"
192.168.1.9 - - [07/Oct/2022:13:44:17 +1000] "GET /play/ssid/123456/type/song/oid/19851/uid/2/name/Sepultura%20-%20Ratamahatta.mp3 HTTP/2.0" 200 6606695 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.34"
```

**Comment by barcoboy** [comment]
Yes I can see the same two entries in my Apache logs each time a democratic song is chosen.

Here are the log entries from Ampache at debug level 5:

```
2022-10-07T04:22:59+00:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-10-07T04:22:59+00:00 [ampache] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Playback\PlayAction" for action "play"
2022-10-07T04:22:59+00:00 [ampache] (play/index) -> Asked for type {song}
2022-10-07T04:22:59+00:00 [demo] (Ampache\Repository\Model\Democratic) -> Unable to find Votes for 17192 of type song
2022-10-07T04:22:59+00:00 [demo] (Ampache\Module\System\Session) -> Session created: 06f391b8a8ec6f0221fb260a6ff1c891
2022-10-07T04:22:59+00:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-10-07T04:22:59+00:00 [ampache] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Playback\PlayAction" for action "play"
2022-10-07T04:22:59+00:00 [ampache] (play/index) -> Asked for type {song}
2022-10-07T04:22:59+00:00 [ampache] (Ampache\Module\System\Session) -> 06f391b8a8ec6f0221fb260a6ff1c891 has been extended to Fri, 07 Oct 2022 06:22:59 +0000 extension length 7200
2022-10-07T04:22:59+00:00 [demo] (Ampache\Module\Playback\Stream) -> No transcode target for: mp3, choosing to resample
2022-10-07T04:22:59+00:00 [demo] (Ampache\Repository\Model\User) -> Login from IP address: nnn.nnn.nnn.nnn
2022-10-07T04:22:59+00:00 [demo] (play/index) -> stream file (/MP3/The Trashmen - Bird Call! - CD #3/Break-Up.mp3}...
2022-10-07T04:22:59+00:00 [demo] (play/index) -> Media type {mp3}
2022-10-07T04:22:59+00:00 [demo] (play/index) -> Registering stream @1665116579 for 3: Trashmen - Break-Up {17192}
2022-10-07T04:22:59+00:00 [demo] (Ampache\Module\User\Activity\UserActivityPoster) -> post_activity: play song by user: 3: {17192}
2022-10-07T04:22:59+00:00 [demo] (lastfm.plugin) -> No session key, not scrobbling (need to grant Ampache to last.fm)
2022-10-07T04:23:01+00:00 [demo] (play/index) -> Stream ended at 6523254 (6523254) bytes out of 6523254

```
I see that in the UserActivityPoster, uid 3 is the user I created for the democratic playing.  I tried deleting that, re-creating it again, assigning it a new API, but still no go.

OK, now I think I am getting somewhere.  I decided to try actually logging into the user I created for the democratic playing, and on that user's front page I do see the recently played songs.  But when I log into my admin user, they don't show up.  They definitely used to show up there, as I never have logged into my democratic user account before... I only set it up to use the API key.  Has this behaviour changed recently, like within the last couple of months?

**Comment by lachlan-00** [comment]
ahh, that's good so there's a privacy issue.

in the user 3(demo) preferences check these prefs `preferences.php?tab=interface`
![image](https://user-images.githubusercontent.com/1305249/194479797-cfd675b0-78a7-4e0d-afd8-d99ac79f595c.png)

the other option that might affect the admin is now_playing_per_user
![image](https://user-images.githubusercontent.com/1305249/194480000-f49a5d7e-8c1c-45c9-ad9f-ca26b4d4926d.png)

The admin user as long as their access level is 'Admin' should always be able to see all.
![image](https://user-images.githubusercontent.com/1305249/194480254-22034864-8bb9-4531-ad78-0e0c5842f203.png)

If your demo user has Share Recently Played information to on then the admin should be able to see this.

I haven't changed anything but there's no reason to say i've broken the code somewhere and not noticed too

**Comment by barcoboy** [comment]
Just confirmed all settings are as you have indicated they should be.

I know it happened around a couple of months ago, and I should have said something then, but didn't figuring someone else would notice and it would be fixed quickly.  Because my system in on a VM, I can take a clone of it and then roll back the git repository and figure out what commit caused the issue to start occurring.

**Comment by stebe** [comment]
I found the commit where this started.  ff232d60144396e5cf2b32e0c7c1c48a03fe1225

**Comment by barcoboy** [comment]
So doing a little more digging, it appears that the patch to show_index.inc.php in commit ff232d60144396e5cf2b32e0c7c1c48a03fe1225 is causing the issue:

```
<div id="recently_played">
    <?php
        (!empty(Core::get_global('user'))) ? Core::get_global('user')->id : -1;
        $data    = Song::get_recently_played($user_id);
        Song::build_cache(array_keys($data));
        $ajax_page = 'index';
        require_once Ui::find_template('show_recently_played.inc.php'); ?>
</div>
```

I was able to fix it on my two Ampache servers, but differently on each server.  On one, I simply changed the "-1" to a "0", and the recently played songs started appearing on my admin's front page.  On the other server, I had to comment out the line and assign the value 0 to user_id manually, and then it worked.  I'm not a PHP programmer, but from what I can see in the code, the first line gets the value of Core::get_global('user'), or if that value is empty, gets the value -1.  My question is... what does Core::get_global('user') refer to?  The currently logged in user, or something else?  And why would my two Ampache servers behave differently executing this code?

**Comment by lachlan-00** [comment]
-1 is a catch all for admin/nonuser parts.
i think i can see this in the get_recently played part

**Comment by lachlan-00** [comment]
i think it's this part
![image](https://user-images.githubusercontent.com/1305249/197939609-154e4b31-1369-40af-a377-8a48c389b44e.png)

set in patch 5 with e30d9b4b9 and develop soon

**Comment by barcoboy** [comment]
Updated but still not working for me.  Now all I have to do is comment out the line:

`$user_id = (!empty(Core::get_global('user'))) ? Core::get_global('user')->id : -1;`

and the recently played come back to the home screen.

**Comment by lachlan-00** [comment]
can you uncomment the debug for the sql query and paste it back here? (`src/Repository/Model/Song.php`)
![image](https://user-images.githubusercontent.com/1305249/198497618-0fbbf86a-2be6-400f-89ed-bde0d6178cd3.png)

**Comment by barcoboy** [comment]
SELECT `object_id`, `object_count`.`user`, `object_type`, `date`, `agent`, `geo_latitude`, `geo_longitude`, `geo_name`, `pref_recent`.`value` AS `user_recent`, `pref_time`.`value` AS `user_time`, `pref_agent`.`value` AS `user_agent`, `object_count`.`id` AS `activity_id` FROM `object_count` LEFT JOIN `user_preference` AS `pref_recent` ON `pref_recent`.`preference`='91' AND `pref_recent`.`user` = `object_count`.`user` LEFT JOIN `user_preference` AS `pref_time` ON `pref_time`.`preference`='92' AND `pref_time`.`user` = `object_count`.`user` LEFT JOIN `user_preference` AS `pref_agent` ON `pref_agent`.`preference`='93' AND `pref_agent`.`user` = `object_count`.`user` WHERE `object_type` = 'song' AND `count_type` = 'stream' AND `object_count`.`user`=1 ORDER BY `date` DESC LIMIT 10

**Comment by lachlan-00** [comment]
thanks, i'm just making some changes to that now.

the function had this weird duplication between users/system pages so i'm just working out the query and splitting that up per user.

**Comment by lachlan-00** [comment]
this should be what you get now in develop as an admin. No user ID checked as you can always see everything

```
SELECT `object_id`, `object_count`.`user`, `object_type`, `date`, `agent`, `geo_latitude`, `geo_longitude`, `geo_name`, `pref_recent`.`value` AS `user_recent`, `pref_time`.`value` AS `user_time`, `pref_agent`.`value` AS `user_agent`, `object_count`.`id` AS `activity_id`
FROM `object_count`
LEFT JOIN `user_preference` AS `pref_recent` ON `pref_recent`.`preference`='91' AND `pref_recent`.`user` = `object_count`.`user`
LEFT JOIN `user_preference` AS `pref_time` ON `pref_time`.`preference`='92' AND `pref_time`.`user` = `object_count`.`user` 
LEFT JOIN `user_preference` AS `pref_agent` ON `pref_agent`.`preference`='93' AND `pref_agent`.`user` = `object_count`.`user` 
WHERE `object_type` = 'song' AND `count_type` = 'stream'
ORDER BY `date` DESC LIMIT 12
```

Then as a user who isn't 100 (admin)
```
SELECT `object_id`, `object_count`.`user`, `object_type`, `date`, `agent`, `geo_latitude`, `geo_longitude`, `geo_name`, `pref_recent`.`value` AS `user_recent`, `pref_time`.`value` AS `user_time`, `pref_agent`.`value` AS `user_agent`, `object_count`.`id` AS `activity_id`
FROM `object_count`
LEFT JOIN `user_preference` AS `pref_recent` ON `pref_recent`.`preference`='91' AND `pref_recent`.`user` = `object_count`.`user`
LEFT JOIN `user_preference` AS `pref_time` ON `pref_time`.`preference`='92' AND `pref_time`.`user` = `object_count`.`user` 
LEFT JOIN `user_preference` AS `pref_agent` ON `pref_agent`.`preference`='93' AND `pref_agent`.`user` = `object_count`.`user` 
WHERE `object_type` = 'song' AND `count_type` = 'stream'
 AND `object_count`.`user` IN (SELECT `user` FROM `user_preference` WHERE (`preference`='91' AND `value`='1') OR `user`='1')
ORDER BY `date` DESC LIMIT 12
```

User pages now use the user object and don't use this function which i think is where all the confusion comes from

**Comment by lachlan-00** [comment]
Admins are allowed to see all rows but if you disable `Share Recently Played information` in the interface settings that will hide you from the other users

![image](https://user-images.githubusercontent.com/1305249/199930905-77a145f3-601a-4233-9cf7-2bc77316e7ee.png)

**Comment by barcoboy** [comment]
Confirmed that it is working as you indicated.  Many thanks!

**Comment by mitchray** [comment]
Closing as it appears to be resolved, reopen if its still relevant
