### ISSUE TITLE
After public-fashion upload, once the musician edits the album the ownership of it is gone

### ISSUE THREAD

**Issue by shangril** [ampache/ampache#4034]
Tested in 6.6.1 due to user report for the Ampache'd "Dogmazic" public upload website. 

The user complained of the fact that after uploading an album, and editing the "release type" which's default is blank, to indicate "EP", the ownership on the Album entity (not songs) was lost, not allowing edits anymore. 

The issue was reproduced with a "user rights" account publishing a new album then editing it, for the publishing process case as following : the artist is already in database, the album title is indicated as "new album..." in the drop-down list  to then add its title. 

The ownership then gets lost if the "album type" is edited, but maybe just any field will cause the issue, I tested for editing "album title" and ownership is lost as well. 

Sorry for not testing with develop branch. Thx.

**Comment by fufroma** [comment]
@lachlan-00 when I have the bug I fix the db manually `update album set album_artist = 4552 where id =  10859 limit 1;` to allow the user to edit his own album

```
MariaDB [ampache]> select count(*) from album where album_artist is null;
+----------+
| count(*) |
+----------+
|       13 |
+----------+
1 row in set (0,000 sec)

MariaDB [ampache]> select count(*) from album ;
+----------+
| count(*) |
+----------+
|     8474 |
+----------+
1 row in set (0,005 sec)

```

very few album impacted, so it may be a pretty new bug. But it's painful for artist

**Comment by lachlan-00** [comment]
Will fix up asap tomorrow. It must not be transferring the user when updating.

I think if I just check the id has changed I can update owner as well.

Will do it first up in the morning

**Comment by lachlan-00** [comment]
Artists and songs have owners (user for artist and user_upload for song)
Albums don't have an owner/user column but they should be updated following the song OR artist.

It may also be that the album_artist is not owned by the user? it could also be a bug checking the user and applying.

The edit check only checks the album artist so it should also respect the songs as you will generally upload a single album instead of one track from the object so it should be a bit looser and allow the user to edit albums they have songs in.
![image](https://github.com/user-attachments/assets/8b043eae-9ab1-4d1c-8cad-c9ed09e0be48)

**Comment by lachlan-00** [comment]
i've got a few test uploads so i'll check what happens when i give them ownership to a regular user.

**Comment by lachlan-00** [comment]
got some family emergency today though so i'll be back later.

I can work around this pretty easy and i think the larger work is putting ownership on the albums themselves which requires a bit more work

**Comment by lachlan-00** [comment]
it all gets done in the album class update function

![image](https://github.com/user-attachments/assets/31bf6b02-b56d-4a93-aa81-2df69f953b27)

it could also be mapping not being updated yet so the artist doesn't get associated with the album so i'd check album_map and artist _map for the new locations. I think the issues is that the mapping tables aren't updated

it could be that this check needs to change
![image](https://github.com/user-attachments/assets/eeefdbb6-b1ff-42e4-b338-092942e81ab4)

Or the artist_map might not be set at all when edited. something like 
`Artist::add_artist_map($this->album_artist, 'album', $this->id);`

(sorry this is all in develop branch so the lines won't match up.)

**Comment by fufroma** [comment]
do you plan to integrate the fix in 6.6.2 or only 7.x ?

**Comment by lachlan-00** [comment]
both, it's an error. this is one of my last todo's before the 6.6.2 release now so once it's done i'll release

**Comment by lachlan-00** [comment]
tested in develop okay the album didn't change id and updated release type, i'll check with 6 now

**Comment by lachlan-00** [comment]
it's definitely the remove_map, the artist isn't being sent in the update data which is weird.

I found a bug with update_from_tags which is fixed so probably close to the answer

**Comment by lachlan-00** [comment]
![image](https://github.com/user-attachments/assets/1517f9e6-1456-494c-bfd1-bc3cbe2b0065)
@fufroma and @shangril i think this is the bug, the fields are just set as strings and allowed to go null when not sent as you can remove album_artist.

so when you update the values are removed as ignored and then that's how we lose ID

**Comment by lachlan-00** [comment]
should be fixed with 2d28009e0

The user's without content_manager would only print the value of the item and then would send null results back to the update function which would remove the values from the album.

**Comment by lachlan-00** [comment]
i'm also putting back field access to non-artist fields. the user should be able to change these
![image](https://github.com/user-attachments/assets/7bf8a893-397c-4472-afac-edfacc53c07e)

**Comment by fufroma** [comment]
@shangril dogmazic is up to date, you can check if the bug is fix and close the issue

@lachlan-00 wow, this was hard to find, good job :)

**Comment by lachlan-00** [comment]
we found a lot of little issues with lower level users here. i might convert myself to a user and play around some more

**Comment by shangril** [comment]
I just tested changing Release Type on the live 6.6.2 Dogmazic site and the
bug is still here.

**Comment by lachlan-00** [comment]
i've looked again as well and it's not working for me. i mist have missed something in my test server that i didn't copy over

**Comment by lachlan-00** [comment]
weird, if i edit once, it disappears, edit twice it comes back

**Comment by lachlan-00** [comment]
of course that's happening....

![image](https://github.com/user-attachments/assets/05303637-b61b-49d4-9056-e843dcdb5fe0)

![image](https://github.com/user-attachments/assets/9fa771f8-ae40-46bc-830c-0d636f517200)

**Comment by lachlan-00** [comment]
found it 750227c95

![image](https://github.com/user-attachments/assets/6c91b076-2685-47f2-831d-0af17e88ecf3)

**Comment by lachlan-00** [comment]
i might do a point release for this it's annoying that it was still there.

**Comment by fufroma** [comment]
@shangril  i applied https://github.com/ampache/ampache/commit/750227c952ed4da3c43777c6335cf1e82ed96263 on your instance, can you do some test?

**Comment by shangril** [comment]
I tested and the bug seems to be fixed.

**Comment by lachlan-00** [comment]
it's a big enough bug to get out

If you edit an album in the UI is might affect more than just user uploads so a good one to find. why it's not in POST for one edit but is in another i'm not sure. seems silly but i'll check further on that
