### ISSUE TITLE
Clicking on a tags column of TV episodes row causes columns menu to disappear

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#704]
While I was stepping through the code to try to understand how the columns get displayed, I tried clicking on an item in the tags column of an TV episode. Not only does the columns menu disappear, but, there is also a second row created which is a duplicate of the row I clicked in, but without the art image.

I haven't made any changes since my last commit and a  pull to merge the latest changes from ampache/develop. Git status indicates working directory is clean.

**Comment by Afterster** [comment]
I'm not sure to understand. Could you add some screenshots? Thanks.

**Comment by wagnered** [comment]
Ok, I didn't notice before that it's bringng up the video tag cloud view with the two episodes (duplicate) even though there is only episode in the database. 

![before clicking on tag data](https://cloud.githubusercontent.com/assets/6115438/5993411/617f6c5a-aa04-11e4-8a22-d0cb976ce930.jpg)

But still it doen't show the columns menu under the filter menu as it did on the Season (episode list) view.

![after clicking on tag data](https://cloud.githubusercontent.com/assets/6115438/5993435/4c0b2584-aa05-11e4-8ed8-647a5e88d775.jpg)

**Comment by Afterster** [comment]
Ok for the missing columns, but I cannot reproduce duplicates. Both have the same video id (same details link)?

**Comment by wagnered** [comment]
Thanks. I guess I left the database in a dirty state, stepping through the code.  There was an aditional entry in the video table, although it didn't seem to be linked to the one tv show entry.

**Comment by wagnered** [comment]
@Afterster,  I think I closed this too soon as the columns menu stilll disappears when sorting on one of the columns.  

Now, I keep a branch updated from upstream,  but clean of any of my own edits to use as a "standard".

**Comment by Afterster** [comment]
Mhh you're right. Should be fixed now, could you confirm?

**Comment by wagnered** [comment]
I forgot to clarify... I've been working with TV shows/episodes, not
music.  The TV shows still aren't sorting correctly, or displaying the
columns drop-down after a sort.

The album/song tables work OK, after a sort on one of the columns, I
still see the columns drop-down menu.



-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by Afterster** [comment]
Ok video sort should be fixed now.

**Comment by wagnered** [comment]
Great, Column menu remains displayed after clicking on a column header.

Low importance,  but clicking on Episodes header doesn't reverse the episode numbers. Maybe add it to a To do list if it's not trivial.

Ampache is doing what I want right now, so I'm going to consider this issue closed.
